-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Aug 21, 2019 at 06:27 PM
-- Server version: 10.1.36-MariaDB
-- PHP Version: 7.2.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `nmn`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` int(11) NOT NULL,
  `catalogue` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `msp` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `type` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `product_name` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `product_img` varchar(2550) COLLATE utf8_unicode_ci NOT NULL,
  `price` int(10) NOT NULL,
  `sale` varchar(1) COLLATE utf8_unicode_ci NOT NULL,
  `product_price` int(10) NOT NULL,
  `product_description` text COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `catalogue`, `msp`, `type`, `product_name`, `product_img`, `price`, `sale`, `product_price`, `product_description`) VALUES
(1, 'Skincare', 'S001', 'CW', 'Nước tẩy trang Chacott For Professionals ', 'https://xachtaynhat.net/wp-content/uploads/2017/09/tay-trang-chacott-e1506678248165.jpg', 600000, '', 600000, 'Nước tẩy trang cleansing water chứa phân tử nước siêu vi RO – hiện nay là công nghệ lọc nước  tạo ra phân tử nước nhỏ hơn 500.000 lần so với sợi tóc con người, có thể len sâu và làm sạch kể cả những vùng dưới sâu bề mặt da.\r\n\r\nFor Sensitive chuyên dành cho da nhạy cảm khiến nước tẩy trang Chacott For Professionals 500ml chiều lòng hết tất cả mọi loại da nhạy cảm và da mụn nhưng vẫn đảm bảo đủ mạnh để cuốn trôi đi các loại mỹ phẩm có độ bám cứng đầu nhất trên cả da nam giới.\r\n\r\nThương hiệu: Chacott\r\n\r\nXuất xứ: Nhật Bản\r\n\r\nQuy cách: 500ml/ chai'),
(2, 'Skincare', 'S002', 'CW', 'Nước tẩy trang Innisfree', 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/8/c/8ca4cae131170590-green-tea-cleansing-water.jpg', 250000, '', 250000, 'Nước tẩy trang Innisfree Green Tea Cleansing Water được chiết xuất từ trà xanh có khả năng làm sạch sâu lớp Make up, bụi bẩn, dầu chỉ với vài lần quẹt nhẹ trên da mà không gây khô da, không làm tổn thương da kể cả những vùng da nhạy cảm. Vẫn giữ được độ ẩm cho da.\r\n\r\nMột điều đặc biệt nữa nước tẩy trang Innisfree Green Tea Cleansing Water  còn có khả năng kháng khuẩn, ngừa mụn, cung cấp vitamin khoáng chất giúp phục hồi độ đàn hồi và nuôi dưỡng da ngày càng khỏe mạnh hơn.'),
(3, 'Skincare', 'S003', 'CW', 'Dầu tẩy trang Muji', 'https://www.muji.us/store/pub/media/catalog/product/cache/cd8219581f6b2a12b25ccafd8df50c0f/4/5/4548076450375_org.jpg', 270000, '', 270000, 'Dầu tẩy trang Muji Oil Cleansing giúp tẩy sạch rất tốt các giúp loại makeup thông thường như kem nền, phấn mắt, phấn má,… có thể tẩy trang được cho cả mắt và môi, hỗ trợ đánh bay các loại kẻ mắt, son và mascara. Sau khi rửa cảm giác da mềm và mát, không khô căng da và cũng không có cảm giác bị ẩm ẩm\r\n\r\nĐược chiết xuất từ Olive tinh dầu, giúp làm sạch nhẹ nhàng cho làn da,đặc biệt không Paraben, không cồn, an toàn cho da.Chất dầu hơi đặc nhưng dễ mát xa trên da. Mang lại cho bạn cảm giác mát mẻ mỗi lần mát xa dầu lên da. Mùi thơm khá nhẹ nhàng'),
(4, 'Skincare', 'S004', 'CW', 'Nước tẩy trang Simple', 'https://product.hstatic.net/1000341639/product/8a.jpeg', 120000, '', 120000, 'Nước tẩy trang Simple Micellar Cleansing Water có xuất xứ từ UK với dung tích 198ml có hiệu quả làm sạch da “mạnh mẽ”, ngay lập tức có thể lấy đi hết bụi bẩn, bã nhờn cùng lớp make up mà không gây kích ứng trên da, kể cả những vùng nhạy cảm như mắt và môi.\r\n'),
(5, 'Skincare', 'S005', 'CW', 'Nước tẩy trang Eucerin', 'https://media-ak.static-adayroi.com/sys_master/hd7/h73/15712939933726.jpg', 320000, '', 320000, 'Eucerin – Dược mỹ phẩm đến từ Đức giới thiệu Pro Acne Acne & Make-up Cleansing Water là nước tẩy trang phù hợp với mọi loại da, đặc biệt là da mụn nhờ:\r\n-Chứa hợp chất APG với khả năng làm sạch sâu mà vẫn đặc biệt dịu nhẹ cho da, kể cả da nhạy cảm và vùng da mắt.\r\n- Arginine làm dịu làn da bị kích ứng, giúp giảm mụn, ngừa mụn và thu nhỏ lỗ chân lông sau 4 tuần.\r\n- Không chứa cồn nên không ảnh hưởng đến lớp dầu tự nhiên, giúp da vẫn ẩm mịn sau bước làm sạch.\r\n\r\nNước tẩy trang Pro Acne thích hợp dùng chung với các sản phẩm trị mụn được kê toa.'),
(6, 'Skincare', 'S006', 'CG', 'Sữa rửa mặt La Roche-Posay', 'https://myphamus.vn/image/cache/data/laro%20che%20srm-508x696.jpg', 350000, '', 350000, 'Gel rửa mặt cho da dầu gel Effaclar Gel (400ml) có công thức được lựa chọn kĩ càng với các thành phần làm sạch dịu nhẹ phù hợp cho da dầu và da mụn nhạy cảm.\r\nNhẹ nhàng loại bỏ tạp chất và bã nhờn dư thừa. Giảm khả năng hình thành mụn đầu đen và giảm bóng nhờn hiệu quả, mang lại làn da sạch thoáng \r\n- Nước khoáng La Roche-Posay: làm dịu da và giảm kích ứng\r\n- Các hoạt chất làm sạch được lựa chọn kĩ càng để tăng hiệu quả làm sạch sâu, giảm bã nhờn trên da\r\n- Zinc pidolate: giảm sự bài tiết bã nhờn'),
(7, 'Skincare', 'S007', 'CG', 'Sữa rửa mặt SVR', 'https://mint07.com/wp-content/uploads/2018/08/sua-rua-mat-da-dau-mun-nhay-cam-svr-sebiaclear-gel-moussant-400ml.jpg', 390000, '', 390000, 'Sữa rửa mặt SVR SebiaClear Gel Moussant (400ml) có khả năng làm sạch sâu rất tốt, đối với các bạn hay phải thường xuyên ra đường, tiếp xúc khói bụi nhiều thì đây quả là một sản phẩm tuyệt vời. Bui bẩn sẽ được lấy đi hết, lỗ chân lông thông thoáng, thúc đẩy quá trình trao đổi chất của da và thấm hút tối đa các sản phẩm dưỡng da.\r\n\r\nChỉ cần sử dụng đều đặn sản phẩm sau 1 tháng bạn sẽ thấy kết quả tuyệt vời mà Sữa rửa mặt SVR SebiaClear Gel Moussant đem lại.\r\n\r\nSản phẩm cực kì dịu nhẹ, không gây kích ứng ngứa rát, có mùi táo xanh nhẹ dễ chịu.'),
(8, 'Skincare', 'S008', 'CG', 'Sữa rửa mặt Eucerin', 'https://product.hstatic.net/1000032844/product/eucerin-pro-acne-solution-cleansing-gel_large.jpg', 425000, '', 425000, 'Eucerin – Dược mỹ phẩm đến từ Đức giới thiệu ProAcne Cleansing Gel là gel rửa mặt phù hợp với mọi loại da, đặc biệt là da nhờn mụn nhờ:\r\n- Không chứa xà phòng và hương liệu\r\n- Chứa 6% Ampho-Tensides giúp loại bỏ bã nhờn dư thừa và làm sạch bụi bẩn trên da\r\n- Có đặc tính ngăn ngừa vi khuẩn mang lại một làn da sạch khỏe\r\n'),
(9, 'Skincare', 'S009', 'CG', 'Sữa rửa mặt Vichy', 'https://beautygarden.vn/Upload/Files/gel-rua-mat-giai-doc-to-vichy-purete-thermale-cleasing-gel.jpg', 550000, '', 550000, 'Vichy Purete Thermale Fresh Cleansing Gel (200ml) là dòng sữa rửa mặt dạng gel cho cảm giác mát dịu tươi mát cho da mặt vào mỗi buổi sáng trước khi đi làm và buổi tối trước khi đi ngủ. Sản phẩm gel rửa mặt Vichy có khả năng tẩy rửa đi những bụi bẩn, tạp chất, dầu nhờn và tác nhân gây hại bám dính sâu trên da mặt và lỗ chân lông. Gel rửa mặt giúp bề mặt da sạch sẽ, giải độc tố và ngăn ngừa ô nhiễm hiệu quả.'),
(10, 'Skincare', 'S010', 'CG', 'Sữa rửa mặt Paula\'s Choice', 'https://paulaschoice.vn/uploads/files/skin-recovery-softening-cream-cleanser.jpeg', 560000, '', 560000, 'Nếu bạn có một làn da nhạy cảm hoặc khó chiều vào những khi thời tiết chuyển lạnh như thế này ( cần một sản phẩm làm sạch êm dịu ) thì Sữa Rửa Mặt Paula’s Choice Skin Recovery (237ml) chính là một lựa chọn sáng suốt. Sữa Rửa Mặt Paula’s Choice Skin Recovery nhẹ nhàng làm sạch bụi bẩn nhưng vẫn giữ lại độ ẩm tự nhiên của da. Khi da bạn đang gặp các vấn đề khác như viêm, mẫn đỏ, kích ứng,khô ngứa thì Sữa Rửa Mặt Paula’s Choice Skin Recovery sẽ vẫn làm sạch nhưng kèm theo là tác dụng làm mềm da và dịu các kích ứng. '),
(11, 'Skincare', 'S011', 'TDC', 'Tẩy da chết Cure', 'https://beautygarden.vn/Upload/Files/tay-te-bao-chet-sinh-hoc-Cure-Natural-Aqua-Gel-Magic-Exfoliator-beauty-garden-1.jpg', 480000, '', 480000, 'Gel tẩy tế bào chết Cure Natural Aqua là sản phẩm tẩy tế bào chết được ưa chuộng nhất ở Nhật Bản với 91% thành phần là nước, không chứa chất bảo quản, không chất tạo mùi nên hoàn toàn an toàn cho làn da. Cure Gel giúp tẩy lớp tế bào chết trên vùng da mặt và toàn thân, kích thích sự tái tạo mới của lớp da phía trong một cách phù hợp nhất để bạn có lớp da mới, mịn màng và tươi trẻ hơn.'),
(12, 'Skincare', 'S012', 'TDC', 'Tẩy tế bào chết Paula\'s Choice', 'https://beautygarden.vn/Upload/Files/tay-te-bao-chet-paulas-choice-Skin-Perfecting-2-BHA-Liquid-Exfoliant-Beauty-garden-1.JPG', 175000, 's', 140000, 'Tẩy da chết Skin Perfecting 2% BHA Liquid Exfoliant  xuất xứ từ Mỹ với dung tích 30ml nhanh chóng thấm vào lớp thượng bì (lớp bề mặt da) và thấm sâu vào lỗ chân lông, từ đó mở các đầu mụn và cải thiện bề mặt da. Kết quả là làm thay đổi một cách thần kỳ vẻ ngoài của da, chức năng da cải thiện, từ đó da sẽ trẻ trung hơn và các kết quả này có thể thấy rõ.'),
(13, 'Skincare', 'S013', 'TDC', 'Tẩy tế bào chết ngọc trai The Face Shop', 'https://thefaceshop360.com/wp-content/uploads/2017/07/tay-te-bao-chet-ngoc-trai-smart-peeling-white-jewel.jpg', 160000, '', 160000, 'Gel tẩy tế bào chết The Face Shop White Jewel (120ml) được chiết xuất từ bột ngọc trai, có tác dụng làm sạch da, làm trắng da một cách tự nhiên, duy trì làn da mịn màng, tăng độ đàn hồi, giảm vết nhăn và ngăn ngừa lão hóa da đồng thời làm săn chắc cơ mặt, giúp khuôn mặt khi trang điểm bắt phấn tốt hơn.'),
(14, 'Skincare', 'S014', 'TDC', 'Tẩy da chết Lancôme', 'https://johnlewis.scene7.com/is/image/JohnLewis/237585036?$rsp-pdp-port-1440$', 800000, '', 800000, 'Tẩy da chết Exfoliating Rose Sugar là sản phẩm mới của thương hiệu Lacôme. Sản phẩm hiện đang làm mưa làm gió tại thị trường Âu – Mỹ. Nó được đông đảo các sao ở Hollywood ưa chuộng nhất hiện nay.\r\n\r\nCông dụng của tẩy da chết Lancôme Exfoliating Rose Sugar Scrub\r\n– Sản phẩm giúp lấy đi các tế bào da chết. Đồng thời nó cũng giúp loại bỏ các tạp chất tồn đọng trên da do bụi bẩn, mỹ phẩm,… Do đó, da của bạn được sạch sâu tận bên trong lỗ chân lông. Nhờ vậy, lỗ chân lông được se khít, làn da mịn màng hơn.\r\n– Tẩy da chết Lacome của Pháp còn giúp da đều màu hơn. Nó sẽ làm mờ các vết thâm do mụn. Nám, tàn nhàng trên da cũng không còn là vấn đề khiến bạn lo ngại.\r\n– Làn da của bạn cũng sẽ trở nên tươi trẻ và hồng hào hơn khi dùng sản phẩm. Đó là do, nó giúp cung cấp nước cân bằng độ ẩm cho da. Vậy nên, da của bạn lúc nào cũng căng tràn sức sống tươi mới.\r\n– Sản phẩm có thành phần hoàn toàn từ thiên nhiên nên an toàn tuyệt đối với da\r\n– Tẩy tế bào chết có hương hoa hồng cùng đường mật ngọt ngào. Nó giúp mang đến cảm giác dễ chịu, thư thái cho người dùng.\r\n– Tẩy tế bào chết Rose Sugar có dạng gel trong suốt. Sản phẩm kết hợp cùng các hạt khoáng chất giúp làm sạch sâu da tối ưu nhất.'),
(15, 'Skincare', 'S015', 'TDC', 'Tẩy da chết Naruko', 'https://mint07.com/wp-content/uploads/2018/09/sua-rua-mat-naruko-tea-tree-purifying-clay-mask-cleanser-in-13.jpg', 279000, '', 279000, 'Gel tẩy tế bào chết trà tràm Naruko (120gr) làm sạch sâu, cân bằng dầu trên da; loại bỏ các tế bào chết, ngăn ngừa tình trạng tắc nghẽn lỗ chân lông; cấp ẩm cho da, kiểm soát dầu; điều hòa da, cải thiện màu da; tăng cường khả năng chống oxy hóa, và giúp bảo vệ da.'),
(16, 'Skincare', 'S016', 'Toner', 'Toner Laneige', 'http://www.laneige.com/vn/vi/laneige-pim-img/product/fresh-calming-balancing-toner/fresh-calming-balancing-toner-01.png', 300000, '', 300000, 'Nước cân bằng Laneige Fresh Calming Toner (250ml) giúp cân đối lượng dầu trên da. Đồng thời giúp giữ cho lớp màng ẩm tự nhiên của da với thành phần nước biển sâu giàu khoáng chất và dịu mát hơn với chiết xuất từ quả vải thiên nhiên.'),
(17, 'Skincare', 'S017', 'Toner', 'Toner SVR', 'https://product.hstatic.net/1000022057/product/sr_pto_97a89246dbb94d96bdf47fb264dfbac2_master.png', 545000, '', 545000, 'Nước cân bằng SVR Physiopure Tonique (200ml) là bước cuối cùng trong quy trình tẩy trang. Bằng cách dưỡng ẩm và loại trừ những bụi bẩn cuối cùng, nước cân bằng giúp làn da chuẩn bị sẵn sàng để tiếp nhận những sản phẩm dưỡng da kế tiếp. Sản phẩm có độ pH sinh lý, không chứa Paraben, cồn, xà phòng, chất tạo màu. Sản phẩm phù hợp với mọi loại da, kể cả da nhạy cảm.\r\n'),
(18, 'Skincare', 'S018', 'Toner', 'Toner hoa cúc Kiehl\'s', 'http://tamkhoashop.com/wp-content/uploads/2017/08/nuoc-hoa-hong-kiehls-hoa-cuc-moonstore1-600x667.jpg', 650000, '', 650000, 'Là dòng sản phẩm chiết xuất từ cúc kim chẩn thảo (Calendula), Toner Kiehl’s hoa cúc Calendula Herbal Extract Alcohol-free (125ml) cực kì dịu nhẹ dành cho da thiên mụn hoặc da dầu.'),
(19, 'Skincare', 'S019', 'Toner', 'Toner Tea Tree The Body Shop', 'https://beautygarden.vn/Upload/Files/nuoc-hoa-hong-The-Body-Shop-Tea-Tree-Skin-Clearing-Toner-hinh-anh1.jpg', 300000, '', 300000, 'Thích hợp cho làn da dễ bị mụn, nước cân bằng dành cho da dầu mụn Tea Tree (250ml) rửa trôi đi mọi bụi bẩn và lớp make up thừa trả lại cho bạn làn da sạch sẽ và không còn bóng dầu.'),
(20, 'Skincare', 'S020', 'Toner', 'Toner Murad', 'http://tiendadecafe.co/wp-content/uploads/2019/02/environmental-shield-essential-c-toner-murad-vitamin-review-product.jpg', 888000, '', 888000, 'Công dụng chính: Phục hồi, cân bằng và bảo vệ da bị hủy hoại qua việc bổ sung độ ẩm, lấy lại sự mềm mại cho da đồng thời chống oxy hóa hữu hiệu kháng gốc tự do\r\nĐối tượng sử dụng: Phù hợp với những làn da thô ráp, mờ xỉn, sạm nám không đều màu. Đặc biệt tốt cho những làn da nào thường xuyên tiếp xúc nhiều với môi trường.'),
(21, 'Skincare', 'S021', 'Serum', 'Serum Vichy', 'http://cdn.nhanh.vn/cdn/store/24031/ps/20190628/serum_duong_da_cap_nuoc_vichy_89_mineral.jpg', 985000, '', 985000, 'Phục hồi, tái tạo da, giúp da trở nên căng mọng và mịn màng hơn bằng cách bổ sung những khoáng chất tương tự như các chất giữ ẩm tự nhiên NMF của da. Bên cạnh đó, sản phẩm còn giúp nuôi dưỡng từ sâu bên trong, cung cấp những dưỡng chất cần thiết cho quá trình tái tạo da hàng ngày. Thành phần nước khoáng trong sản phẩm mang đến hiệu quả cho cả ngoài và trong nên da bạn vừa được dưỡng ẩm căng mọng từ bên trong đồng thời mịn mướt cả bên ngoài.'),
(22, 'Skincare', 'S022', 'Serum', 'Serum Murad', 'https://www.muradvietnam.vn/Data/Sites/1/Product/632/porcelain-serum.jpg', 3450000, '', 3450000, 'WHITE BRILLIANCE® PORCELAIN SERUM (30ml) là sự kết hợp của 4 công nghệ làm sáng da mạnh mẽ nhưng lại vô cùng an toàn, giúp bạn có được làn da trắng sáng trong suốt lấp lánh như hạt sương mai.'),
(23, 'Skincare', 'S023', 'Serum', '', 'https://s3-ap-southeast-1.amazonaws.com/misskick/wp-content/uploads/2017/12/12174926/08-LANEIGE-White-Plus-Renew-Original-Essence-EX-40-ml.jpg', 1100000, '', 1100000, 'Laneige White Plus Renew Original Essence EX với thành phần thiên nhiên là lá trà xanh và cây bạch thảo – vốn là thực vật dùng để làm thuốc nên loại serum này sẽ rất an toàn cho da. Đặc biệt là serum hoạt động bằng cách thủy phân Melanin, thẩm thấu sâu vào bên trong, bao bọc và làm “mất màu” các hắc sắc tố, khiến chúng trở nên trong suốt giúp làn da của bạn trở nên sáng mịn, đều màu hơn và mịn màng như tơ.'),
(24, 'Skincare', 'S024', 'Serum', 'Serum Clinique', 'https://m.sephora.com/productimages/sku/s1629971-main-zoom.jpg', 1500000, 's', 1200000, 'Smart Custom-Repair Serum chữa trị chính xác những thương tổn bạn nhìn thấy và những tổn thương bạn không nhìn thấy được. Da bị tác hại phát đi tín hiệu cầu cứu, Smart Custom-Repair Serum hiểu những tín hiệu này và kích hoạt những thành phần phù hợp để chữa trị thương tổn. Nếu thành phần nào không cần thiết cho trường hợp này, chúng sẽ giữ yên trong tư thế sẵn sàng. \r\n\r\nTinh Chất Thông Minh Chữa Trị Tương Thích Clinique Smart Custom-Repair Serum chữa trị tập trung khi da cần, ở vùng da cần và các thử nghiệm lâm sàng đã minh chứng hiệu quả. Clinique cho biết, sau 12 tuần người sử dụng sẽ cảm nhận được sự cải thiện rõ rệt sắc da không đều màu, đốm sậm màu, sạm da, đường nhăn, rãnh nhăn và chảy xệ. '),
(25, 'Skincare', 'S025', 'Serum', 'Serum Laroche-Posay Hayalu B5', 'https://cdn.shopify.com/s/files/1/0088/1937/6188/products/3337875583626_3d4da7e5-f1f1-45b8-b259-eeb16e482bfa_2000x.jpg?v=1560965271', 780000, '', 780000, 'Công thức phục hồi da đặc biệt độc đáo gồm hai loại axit hyaluronic thuần khiết, vitamin B5 và Madecassoside, giúp làm săn chắc da, sửa lại rào cản của da và kích hoạt sự đổi mới của da. Tinh chất HYALURONIC B5 ACID cấp ẩm mạnh mẽ này cực kì dễ thẩm thấu, làm mềm da và bổ sung tăng cường dưỡng chất, đồng thời giảm thiểu sự xuất hiện của đường nhăn và nếp nhăn cho kết quả mượt mà, trẻ trung. Làm cho da mặt căng và tươi mới , khôi phục tính đàn hồi của da . Trông bạn rạng rỡ trẻ trung và đầy sức sống hơn.'),
(26, 'Skincare', 'S026', 'KCN', 'Kem chống nắng Eucerin', 'https://mint07.com/wp-content/uploads/2019/05/kem-chong-nang-eucerin-photoaging-control-spf50-fair-tinted1.jpg', 350000, '', 350000, 'Với màng lọc UVA/UVB theo tiêu chuẩn châu Âu cùng công thức chứa chiết xuất cam thảo - chất chống oxy hoá hiệu quả giúp bảo vệ da khỏi tác hại của ánh nắng mặt trời. Kết hợp với acid Glycyrrhetinic là chất giúp hỗ trợ quá trình tái tạo da.\r\n\r\nSản phẩm tạo nên lớp che phủ lâu dài với tông màu sáng nhạt tạo nên vẻ tự nhiên cho da. Kết cấu kem nhẹ, không mùi, không chứa nhóm chất bảo quản Parabens, không gây dị ứng và thích hợp cho da nhạy cảm.'),
(27, 'Skincare', 'S027', 'KCN', 'Kem chống nắng Laroche-Posay', 'https://www.kuteshop.vn/wp-content/uploads/2016/04/Kem-ch%E1%BB%91ng-n%E1%BA%AFng-La-Roche-Posay-Anthelios-Shaka-Fluide-SPF-50-50ml.jpg', 305000, '', 305000, 'Kem chống nắng dành cho da nhạy cảm, đặc biệt là những làn da cực kỳ nhạy cảm với ánh nắng mặt trời, với độ bảo vệ cao SPF 50+, bảo vệ da trước những tác hại từ ánh nắng & ô nhiễm: lão hóa sớm, đốm nâu, kích ứng ánh nắng.'),
(28, 'Skincare', 'S028', 'KCN', 'Kem chống nắng Vichy', 'https://beautygarden.vn/Upload/Files/kem-chong-nang-Vichy-Mattifying-Dry-Touch-Face-Fluid-50ml.jpg', 385000, '', 385000, 'Ngoài tác dụng bảo vệ làn da khỏi ánh nắng mặt trời, kem chống nắng Vichy Ideal Soleil SPF 50 còn bổ sung thêm những thành phần chiết xuất từ rễ gừng giúp nuôi dưỡng làn da trở nên săn chắc hơn. Thành phần cam kết không chứa dầu và Paraben. Điều đó hạn chế tình trạng gây tắc nghẽn lỗ chân lông có thể gây nên mụn. Đồng thời với thời tiết mùa Hè thì một sản phẩm không chứa dầu chính là sự lựa chọn đúng đắn để bảo vệ lớp trang điểm bám trên da cả ngày cũng như tránh được tình trạng “mặt như chảo dầu”.'),
(29, 'Skincare', 'S029', 'KCN', 'Kem chống nắng Bioderma', 'http://tamkhoashop.com/wp-content/uploads/2018/03/bioderma-photoderm-max-14648-600x800.jpg', 279000, '', 279000, 'Kem chống nắng Bioderma Photoderm Max Aqua Fluide SPF 50+ – kem chống nắng sử dụng công nghệ Cellular Bioprotection độc quyền từ Bioderma giúp bảo vệ các tế bào da khỏi các gốc tự do đồng thời kích thích khả năng “tự” phòng vệ của da dưới ánh nắng mặt trời. Bioderma Photoderm Max Aqua Fluide SPF 50+ sở hữu chất kem mỏng, mướt, lỏng như sữa nên thấm vào da cực nhanh mà ko gây nhờn dính, da sáng lên “chun chút” nhưng sáng đều và tất nhiên, không để lại vệt trắng bờ “xấu xí” trên da. Công thức Anti – shine giúp bề mặt da không bóng nhờn, matte và mịn, đồng thời kem chống nắng không chứa hương liệu, paraben giúp Photoderm Max Aqua Fluide phù hợp cả với những làn da nhạy cảm nhất. Với chỉ số SPF 50, PPD 24 cùng khả năng chống thấm nước cao, Bioderma Photoderm Max Aqua Fluide cực kì thích hợp để dùng hàng ngày và trong cả những hoạt động ngoài trời, trên những chuyến đi xa, để những ngày “nắng gắt” sẽ không còn là “mối lo” mỗi sáng mai thức dậy của những cô gái xinh tươi.'),
(30, 'Skincare', 'S030', 'KCN', 'Kem chống nắng Anessa', 'https://hangcapnach.com/wp-content/uploads/2016/04/kem-chong-nang-shiseido-anessa-perfect-uv-sunscreen-skincare.jpg', 550000, '', 550000, 'Anessa Perfect UV Sunscreen thuộc dòng kem chống nắng Anessa được ưa chuộng nhất tại Nhật Bản (Sản phẩm của Shiseido – Made in Japan) Là loại kem chống nắng cực mạnh SPF50+ , bảo vệ da khỏi tia cực tím . Ko bị dính bết , thoa lên da khô ngay ko bị dính vào quần áo.'),
(31, 'Food', 'F001', '', 'Viên uống DHC Collagen', 'https://nuty.vn/wp-content/uploads/2018/05/dhc-4.jpg', 389000, '', 389000, 'DHC Collagen có nguồn gốc từ da cá biển Nhật Bản giúp hỗ trợ bổ sung collagen\r\nNgoài ra, sản phẩm giúp bổ sung thêm hỗn hợp các vitamin B1, B2 giúp làm đẹp da.\r\n'),
(32, 'Food', 'F002', '', 'Viên uống DHC Collagen 32 loại rau củ', 'https://japana.vn/uploads/product/2019/04/19/1555692402--qua-dhc-nhat-ban-sieu-thi-nhat-ban-japana-21.jpeg', 369000, '', 369000, 'Viên uống 32 loại rau củ DHC nổi bật với công dụng giúp bổ sung 32 loại chất xơ và vitamin, được chiết xuất từ 32 loại rau củ khác nhau. Viên rau củ DHC Premium là tổng hợp của 32 loại rau xanh đã được chọn lọc và bổ sung hàm lượng cân đối thực sự rất tốt cho sức khỏe.'),
(33, 'Food', 'F003', '', 'Viên uống DHC vitamin C', 'https://xachtaynhat.net/wp-content/uploads/2017/09/Vitamin-C-DHC.png', 150000, '', 150000, 'Công dụng nổi bật của Viên uống DHC Vitamin C 20 ngày bên cạnh hiệu quả làm đẹp da, còn giúp giải độc gan, lưu thông máu, thậm chí còn có khả năng phòng chống ung thư hiệu quả. '),
(34, 'Food', 'F004', '', 'Viên uống DHC Vitamin E ', 'http://bizweb.dktcdn.net/100/180/838/products/vien-uong-bo-sung-vitamin-e-dhc-tghn-1-jpeg.jpg?v=1533830776420', 195000, '', 195000, 'Viên uống bổ sung vitamin E DHC của Nhật Bản được chiết xuất từ dầu thực vật tự nhiên, có tác dụng hỗ trợ và làm mịn da cũng như điều trị sẹo sau mụn, chống lão hóa,  đồng thời cải thiện tình trạng tóc xơ rối dễ gãy rụng. Bổ sung vitamin E cũng giúp giảm nguy cơ gây ung thư vú ở phụ nữ.'),
(35, 'Food', 'F005', '', 'Viên uống mầm đậu nành DHC', 'https://mypham.tv/wp-content/uploads/2018/05/mam-dau-nanh-dhc-0.jpg', 240000, '', 240000, '- Tinh chất mầm đậu nành DHC 20 ngày 80 viên của Nhật với hoạt chất insoflavone được chiết xuất từ đậu nành có tác dụng rất tốt cho sức khỏe, sắc đẹp của phụ nữ giúp cải thiện nhiều triệu chứng tiền mãn kinh như: mất ngủ, đau đầu, giảm trí nhớ, loãng xương, người mệt mỏi, đau xương khớp, ra mồ hôi trộm.\r\n\r\n- Đặc biệt, sản phẩm Viên uống mầm đậu nành DHC Nhật Bản còn giúp giảm nguy cơ các bệnh nguy hiểm ở nữ giới như: ung thư tử cung hay ung thư vú. Đây là một trong các loại viên uống DHC được nhiều chuyên gia khuyên phái đẹp nên dùng.'),
(36, 'Food', 'F006', '', 'Viên uống bổ sung kẽm DHC', 'https://japana.vn/uploads/product/2019/04/19/1555639661-bo-sung-kem-dhc-sieu-thi-nhat-ban-japana-2323.jpeg', 195000, '', 195000, 'Viên uống bổ sung kẽm DHC là một trong những sản phẩm bổ sung kẽm hiệu quả cho cơ thể, giúp đem lại nhiều công dụng tuyệt vời cho xương khớp, da, não bộ, mắt...Viên uống bổ sung kẽm DHC do Nhật Bản sản xuất được đông đảo người tiêu dùng trên toàn thế giới ưa chuộng và sử dụng.\r\n\r\nViên uống bổ sung kẽm DHC là một trong những loại viên uống vitamin của DHC đáng dùng nhất hiện nay, đem lại sức khỏe và sắc đẹp toàn diện'),
(37, 'Food', 'F007', '', 'Viên uống DHC chiết xuất quả việt quất', 'http://product.hstatic.net/1000041671/product/vien-uong-duong-mat-dhc-blueberry-extract-1_grande.jpg', 240000, '', 240000, 'Viên uống chiết xuất quả việt quất DHC chứa các sắc tố tự nhiên, đặc biệt Quả việt quất giàu chiết xuất Anthocyanin kết hợp với hoa cúc và các Vitamin, đem lại nhiều công dụng cho cơ thể.'),
(38, 'Food', 'F008', '', 'Viên uống bổ sung DHA DHC', 'https://mypham-nhatban.com/media/catalog/product/cache/1/thumbnail/600x600/9df78eab33525d08d6e5fb8d27136e95/1/6/1661.jpg', 320000, '', 320000, 'Viên uống bổ sung DHA DHC là sản phẩm thích hợp dành cho những người không thích ăn cá hoặc không có điều kiện để bổ sung đầy đủ dưỡng chất hằng ngày. Đây cũng được đánh giá là một trong những sản phẩm DHC nổi bật trên thị trường.'),
(39, 'Food', 'F009', '', 'Viên uống trắng da COIX DHC', 'https://japanshop.jweb.vn/uploads/japanshop/images/12_2.jpg', 280000, '', 280000, 'Viên uống trắng da Coix Extract DHC được chiết xuất từ hạt Coix, là một loại thảo dược mọc quanh năm ở khu vực Đông Dương có tác dụng làm trắng da, bổ sung và dưỡng ẩm cho da giúp ngăn ngừa hiện tượng khô da và da nứt nẻ.'),
(40, 'Food', 'F010', '', 'Viên uống DHC nhau thai cừu', 'https://www.hangngoainhap.com.vn/images/201809/goods_img/2517_P_1537810772548.jpg', 180000, '', 180000, 'TOP các loại DHC Nhật Bản tốt nhất hiện nay không thể không kể đến viên uống DHC nhau thai cừu. Viên uống DHC chứa thành phần Nhau thai cừu 3600mg DHC, ngoài ra sản phẩm còn bổ sung các thành phần Vitamin B2 cùng Axit Amin, Carbohydrate, Enzyme, thành phần dầu Olive, thành phần sáp ong và các khoáng chất cần thiết giúp nuôi dưỡng và bổ sung sâu từ các tế bào bên trong cơ thể, từ đó giúp cơ thể luôn khỏe mạnh, giúp phục hồi nét thanh xuân và đánh bật dấu hiệu của tuổi tác.'),
(41, 'Food', 'F011', '', 'Viên uống mọc tóc và làm dày tóc Volume top DHC', 'https://www.konvy.com/static/team/2018/1025/15404561328196_600x600.jpg', 730000, '', 730000, 'Viên uống mọc tóc và làm dày tóc volume top DHC được chiết xuất từ 14 thành phần tự nhiên bổ sung giúp nuôi dưỡng cho da đầu bạn được khỏe mạnh, giúp kích thích sự phát triển của tóc, giúp mọc tóc và làm dày tóc hiệu quả.'),
(42, 'Food', 'F012', '', 'Viên uống Glucosamin + Sụn vi cá + CBP DHC', 'https://dotobjyajpegd.cloudfront.net/photo/5d388327849a5e0be806c331_l', 520000, '', 520000, 'Viên uống Glucosamin + Sụn cá + CBP của DHC chứa hợp chất tự nhiên giúp: nuôi dưỡng cấu trúc các mô liên kết trong sụn và dịch khớp, làm dứt nhanh chóng triệu chứng viêm khớp, sưng phù khớp. Cải thiện phục hồi chức năng các khớp.'),
(48, 'Tool', 'T001', '', 'Silcot Bông Trang Điểm (bông tẩy trang) Nhật Bản', 'https://salt.tikicdn.com/cache/550x550/ts/product/5a/52/9f/935e148879bfeb6eab0c4e1b273eee37.jpg', 30000, '', 30000, 'Hộp 30 miếng'),
(49, 'Tool', 'T002', '', 'Bông tẩy trang Emily', 'https://huongviva.com/wp-content/uploads/2018/10/bong-tay-trang-emily-1.jpg', 28000, '', 28000, '120 miếng'),
(50, 'Tool', 'T003', '', 'Bông tẩy trang Ipek', 'https://salt.tikicdn.com/cache/550x550/ts/product/e5/5d/cf/5bd258c1cc57e92359f4b709b95e0e20.jpg', 23000, '', 23000, '150 miếng'),
(51, 'Tool', 'T004', '', 'Bông tẩy trang Jomi', 'https://salt.tikicdn.com/ts/product%2F98%2Fa1%2F84%2F4e761298557238e2ade9ad142cd78e55.jpg', 25000, '', 25000, '120 miếng'),
(52, 'Tool', 'T005', '', 'Bông tẩy trang Miniso ', 'https://media.sheis.vn/beautyProductPhoto/g20/s600x600/Beauty-3081-635996826359409727.jpg', 40000, '', 40000, '1000 miếng'),
(53, 'Tool', 'T006', '', '', 'https://product.hstatic.net/1000201681/product/mat-na-dang-vien-nen-miniso-japan_large.jpg', 100000, '', 100000, 'Mặt nạ nén Miniso Nhật Bản với thành phần chiết xuất từ lá tre cùng các dưỡng chất chăm sóc da được thiết kế dạng viên kẹo nhỏ xinh, dễ dàng sử dụng, giúp cung cấp độ ẩm và dưỡng da sáng mịn là sản phẩm mặt nạ mới lạ, độc đáo được rất nhiều người yêu thích sử dụng.'),
(54, 'Tool', 'T007', '', 'Hộp cọ trang điểm 3CE', 'https://images.depxinh.net/products/2018/6/17089/default/hop-co-3ce-nen-dep-xinh.jpg', 90000, '', 90000, 'Hộp cọ trang điểm 3CE Mini Brush Kit 7 Cây đủ đáp ứng cho trang điểm cá nhân được thiết kế mềm mại, mịn mại, sợi lông được làm từ nguyên liệu tự nhiên vô cùng an toàn.'),
(55, 'Tool', 'T008', '', 'Bộ cọ trang điểm MAANGE', 'https://my-test-11.slatic.net/p/86e38aa5019da7b9c0174e8eda2286dc.jpg', 90000, '', 90000, ''),
(56, 'Tool', 'T009', '', 'Bộ cọ trang điểm cá nhân 12 cây Naked3', 'https://camilasantamariastore.com.co/364-large_default/set-de-brochas-naked-3.jpg', 110000, '', 110000, ''),
(57, 'Tool', 'T010', '', 'Kẹp làm cong mi Innisfree Eyelash Curler', 'https://cuahanglamdep.com/images/detailed/1/05kepmiinnis-2.jpg', 100000, '', 100000, ''),
(58, 'Tool', 'T011', '', 'Máy rửa mặt Pebble Lisa Face Washing Machine', 'https://mint07.com/wp-content/uploads/2017/09/may-rua-mat-pebble-lisa-face-washing-machine.jpg', 670000, '', 670000, 'Với đầu cọ silicone mềm mại được nhập khẩu từ Mỹ, da bạn được làm sạch sâu lại càng thêm khỏe, bất kể là da thường, da dầu, hỗn hợp hay nhạy cảm.  Kết hợp máy với các sản phẩm skincare như serum, kem dưỡng giúp dưỡng chất thẩm thấu sâu vào da hơn, nuôi dưỡng làn da thêm hiệu quả.'),
(59, 'Tool', 'T012', '', 'Bộ 13 Bông Mút Trang Điểm Keli Sponge Makeup', 'https://vn-test-11.slatic.net/original/6a79ad4b2017ba31798f109253f9637a.jpg', 48000, '', 48000, ''),
(60, 'Makeup', 'MF001', 'Foundation', 'Chanel Les Beige Healthy Glow Foundation', 'https://www.chanel.com/images///w_0.43,h_0.43,c_crop/q_auto,f_jpg,fl_lossy,dpr_2/w_1920/les-beiges-packshot-default-184216-8806527041566.jpg', 1250000, 's', 1000000, 'Kem nền Chanel Les Beiges Healthy Glow Foundation sẽ chẳng làm bạn thất vọng!\r\nChanel là một thương hiệu cao cấp và nổi tiếng hàng đầu thế giới, không chỉ về lĩnh vực thời trang như quần áo, phụ kiện, túi xách, mà trong lĩnh vực mỹ phẩm, Chanel cũng chứng tỏ được sức hút của mình. Kem nền Chanel Les Beiges Healthy Glow Foundation là sản phẩm kem nền cao cấp sẽ mang lại cho bạn một lớp nền trang điểm hoàn hảo với vẻ đẹp tự nhiên và khỏe khoắn. \r\n\r\n Kem nền Chanel Les Beiges Healthy Glow Foundation tuy là kem nền nhưng chất kem mỏng nhẹ, dễ tán, để những phụ nữ không còn lo ngại về việc sử dụng kem nền. Che phủ khuyết điểm tốt nhưng làn da nhìn vẫn tự nhiên.'),
(61, 'Makeup', 'MF002', 'Foundation', 'Anastasia Beverly Hills Cream Stick Foundation ', 'https://www.anastasiabeverlyhills.com/dw/image/v2/BBLL_PRD/on/demandware.static/-/Sites-anastasia-master-catalog/default/dw68ed0486/images/Redesign/Rescaled/abh-stick-foundation-warm-natural-a.jpg?sw=1376&sh=1376&sm=fit', 680000, '', 680000, 'Anastasia Beverly Hills Stick Foundation có cấu trúc dạng cream đặc, hơi sệt nhưng lại rất dễ tán khi lên da. Sản phẩm để lại lớp nền không phải dạng dewy (trong, bóng) cũng không phải dạng matte (lỳ) mà là sự kết hợp của cả dewy và matte, mang lại hiệu ứng nền cực kỳ tự nhiên, mỏng nhẹ và ẩm mượt.\r\n'),
(62, 'Makeup', 'MF003', 'Foundation', 'Laneige Water Glow Jel Foundation', 'https://www.laneige.com/int/en/resource/img/product/water-glow-gel-foundation_01.png', 495000, 's', 396000, '- Water Glow Gel Foundation có độ che phủ tốt, đem lại độ mướt cho làn da của bạn, hơn nữa lớp finish hoàn toàn lì phù hợp cho các bạn da dầu hay hơn hết là các nàng ở các nước khí hậu nóng ẩm như Việt Nam, kiềm dầu ổn từ 5-6 tiếng.\r\n\r\n- Khả năng bám dính cao giúp dưỡng ẩm, che phủ làn da, mang lại gương mặt mịn màng & trẻ trung.\r\n\r\n- Lớp nền với 70% độ ẩm : Kết cấu với độ ẩm ổn định 70% giúp lớp nền dưỡng ẩm, sáng và che phủ hoàn hảo.\r\n\r\n- Mang lại cảm giác mềm mại, mịn màng không gây nếp nhăn khi dặm lại nhiều lần vì các hạt bột dẫn xuất amino axit bám chặt vào da không gây cảm giác dày và bết dính.'),
(63, 'Makeup', 'MF004', 'Foundation', 'Dior Diorskin Forever Undercover Concealer', 'https://www.dior.com/beauty/version-5.1563986503603/resize-image/ep/870/580/90/0/horizon%252Fcovers%252FY0339200_F033920020_E01_ZHC.jpg', 610000, '', 610000, 'Tạo lớp phủ ngụy trang đầy đủ với một lớp. Với sắc tố hơn 25% so với Chất lỏng Forever Diorskin của da, kem che khuyết điểm này sẽ giấu và vô hiệu hóa sự không hoàn hảo cả ngày. Công thức dưỡng ẩm của nó vẫn thoải mái, và sẽ không nếp nhăn, nứt, hoặc giải quyết thành đường dây.\r\nTRANG ĐIỂM\r\nConorsaler Forever Concealer của Diorskin Forever có kết cấu Matte tươi và cung cấp độ che phủ đầy đủ, che giấu vết nứt bằng một lần vuốt.'),
(64, 'Makeup', 'MF005', 'Foundation', 'Fenty Pro Filt\'r Primer', 'https://www.fentybeauty.com/dw/image/v2/AAXW_PRD/on/demandware.static/-/Sites-itemmaster_FNT/default/dwb5ac687a/hi-res/31698_alt1.jpg?sw=550', 765000, '', 765000, 'Thiết kế tinh tế và tối giản như cùng dòng sản phẩm kem nền của hãng Fenty với vòi phun cực tiết kiệm và dễ dàng lấy kem khi sử dụng Sản phẩm có tác dụng che phủ và làm mờ lỗ chân lông, kiểm soát lượng dầu thừa trên da. Bên cạnh đó, em ấy còn giúp bạn nâng tone nhẹ và mang đến hiệu ứng mềm mịn mà không hề gây khô da. Sản phẩm có kết cấu lỏng nhẹ, khi apply lên da sẽ thấm ngay lập tức mà không hề gây cảm giác bết dính, khó chịu. Glycerin có trong thành phần sẽ giúp bạn dưỡng ẩm để lớp nền luôn căng mướt và hạn chế xuống tone. Đồng thời hạn chế tình trạng đổ dầu trên da. Thương hiệu: Fenty Xuất xứ: USA Trọng lượng: 4ml(Tách set Sephora)'),
(65, 'Makeup', 'MF006', 'Powder', 'Fenty Beauty Pro Filt\'r Loose Setting Powder', 'https://www.fentybeauty.com/dw/image/v2/AAXW_PRD/on/demandware.static/-/Sites-itemmaster_FNT/default/dw154ad581/hi-res/FB30016_FB9005_alt2.jpg?sw=550', 360000, '', 360000, 'Phấn phủ Fenty Beauty by Rihanna với độ bám màu cùng lâu trôi ấn tượng dành cho mọi cô gái thích trang điểm.\r\nKhông những giúp che phủ, kiềm dầu mà còn che khuyết điểm thần kỳ, che được cả những nốt tàn nhang, đốm mụn hay những nếp nhăn nhỏ.\r\nVới một tone màu trung tính phấn phủ của Rihanna thích hợp dành cho mọi cô gái với nhiều màu da khác nhau như da trắng, da nâu hay da vàng của Châu Á mà không gây bệt màu.'),
(66, 'Makeup', 'MF007', 'Powder', 'Too Faced Born This Way Loose Setting Powder', 'https://images.asos-media.com/products/too-faced-born-this-way-ethereal-loose-powder-translucent-medium/10600112-2?$XXL$&wid=513&fit=constrain', 399000, '', 399000, '  Dòng phấn phủ khắc phục tất cả các lỗi make up để tạo nên một cái nhìn mượt mà và ngăn ngừa bã nhờn trong suốt cả ngày.\r\n  Thành phần bột ngọc trai pha lẫn các nguyên liệu tự nhiên khác tạo nên loại bột mịn màng.\r\n  Em này phù hợp với mọi tone màu da nhé và điều đặc biệt là em này với công thức được điều chế từ nước dừa giúp dưỡng ẩm da cực tốt và hoa hồng Alpine giúp da sáng rạng ngời, mềm mịn và làm cho bạn trẻ ra trông thấy luôn ấy.\r\n  Độ che phủ hoàn hảo .\r\nSản phẩm có kết cấu cực mịn, tạo cảm giác khô thoáng không gây bí da, mang lại vẻ đẹp tự nhiên cho làn da sau khi trang điểm.\r\n  Sp không chứa  Parabens ,Sulfates & Phthalates.'),
(67, 'Makeup', 'MF008', 'Powder', 'Coulorpop No Filter Loose Setting Powder', 'https://cdn.shopify.com/s/files/1/2487/3358/products/loose-powder-lineup_800x1200_7a7b1daf-6eb6-4b2b-b07d-7f90e374a78a_800x.jpg?v=1530381260', 329000, '', 329000, '  Em này siêu nóng lên đợt nhờ chị Kathleenlights và anh Jeff lăng xê đây ạ . Giá thành thì siêu yêu nhưng chất lượng siêu tốt. Phấn phủ mịn , mượt , phủ lên da giúp kiềm dầu cực tốt dành cho da dầu nhưng da khô cũng ko hề bị cakey nha chị em. Chị Kath là một ng phải gọi siêu kén về phấn phủ , còn anh Jeff là toàn xài phấn lamer , chanel ... còn mê e này là phải hiểu ạ. Và colourpop tuy là một hãng giá drugstore nhưng toàn bộ sản phẩm đều Made in usa nhé.\r\n  Một hộp dung tích 8,5g with box . H bán màu Translucent ( không màu ) nên từ da trắng sáng đến da medium tan đều dùng được hết nha. '),
(68, 'Makeup', 'MF009', 'Powder', 'Diorskin Nude Air Loose Powder', 'https://www.dior.com/beauty/version-5.1563986503603/resize-image/ep/870/580/90/0/horizon%252Fcovers%252FY0720350_F072035020_E01_ZHC.jpg', 1000000, '', 1000000, '  Kết cấu nhẹ nhàng, thoáng khí, không có cảm giác khó chịu, bức bí dù giữa trời mùa hè nắng nóng, không còn tình trạng mốc hay loang lỗ. Với những mảng da ửng đỏ ngay cánh mũi có thể được che phủ khá tốt, làm cho làn da đều màu hơn.\r\n  Độ bền màu cao ngay cả khi bạn đổ nhiều mồ hôi, thời gian sử dụng kéo dài  giúp bạn tiết kiệm thời gian, công sức khi phải dặm phấn nhiều lần. Giữ lớp make up bền màu, lâu trôi, không bị xỉn màu, xuống tone, giúp da luôn sáng khỏe.'),
(69, 'Makeup', 'MF010', 'Powder', 'Jeffree Star Magic Star Setting Powder', 'https://www.princesspolly.com/media/catalog/product/cache/7/image/1000x1353/9df78eab33525d08d6e5fb8d27136e95/1/_/1_156_67.1556786596.jpg', 450000, '', 450000, '  Phấn Bắt Sáng Jeffree Star Cosmetics Skin Frost Highlighting Powder nếu các nàng đang tìm kiếm một loại phấn bắt sáng \"an toàn\", cực kì tiện lợi mang lại vẻ đẹp tự nhiên và thanh thoát hơn cho khuôn mặt bạn sau khi Makeup thì Skin Frost hoàn toàn có thể đáp ứng được yêu cầu đó. \r\n  Skin Frost Highlighting Powder với vỏ hộp cầm nặng tay, gương long lanh rõ xịn, chất lượng như vậy tính ra thì không quá đắt.'),
(70, 'Makeup', 'MF011', 'Blusher', 'Kylie\'s Hopeless Romantic Blush', 'https://cdn.shopify.com/s/files/1/1133/5964/products/hopeless.jpg?v=1507255882', 240000, '', 240000, '  Sau thành công của cơn sốt những em son kem lì đình đám, Kylie lại tiếp tục khiến các tín đồ làm đẹp “dậy sóng” khi ra mắt bộ sưu tập phấn má hồng Kylie Pressed Blush Powder không chỉ đẹp mà còn cực chất nữa. \r\n\r\n Bộ sưu tập hội tụ toàn những tone màu cơ bản, dễ sử dụng lại phù hợp với mọi tone màu da. Bao gồm các tone màu từ nhẹ nhàng cho đến các tone màu đậm quyến rũ, tha hồ cho các nàng biến hóa với đủ phong cách trang điểm khác nhau.'),
(71, 'Makeup', 'MF012', 'Blusher', 'Glossier Cloud Paint Blusher', 'http://thebeautylookbook.com/wp-content/uploads/2017/03/Glossier-Cloud-Paint-Review.jpg', 159000, '', 159000, 'Glossier tuy không phải một thương hiệu mỹ phẩm quen thuộc tại Việt Nam nhưng lại cực kỳ phổ biến với các cô nàng mê làm đẹp trên thế giới. Má hồng kem nổi tiếng Cloud Paint đến từ thương hiệu này rất đặc biệt, có kết cấu kem nằm giữa dạng gel và dạng cream, vừa đủ dày để lưu giữ màu trên má cả ngày, vừa có thể tạo hiệu ứng lên màu một cách tự nhiên nhất có thể.\r\n\r\nGlossier Cloud Paint cho hiệu ứng ửng hồng tự nhiên như da thật vậy. Thường thì sẽ mix 2 màu Beam và Dusk với nhau để cho ra màu sắc hồng hào tự nhiên nhất.'),
(72, 'Makeup', 'MF013', 'Blusher', 'Innisfree Smart Drawing Cream Blusher', 'https://www.roseroseshop.com/image/data/brand/innisfree/light/innisfree_mt_165_02_light.jpg', 99000, '', 99000, 'Phấn má dạng kem cho lớp nền bóng khỏe,tươi sáng.\r\nLớp hoàn thiện bóng mịn và lâu trôi\r\nTrang điểm dễ dàng mà vẫn thật công phu cùng Smart Pen Brush: tích hợp đầu cọ siêu mảnh giúp tăng hiệu quả mỏng mịn, tiết kiệm thời gian trang điểm.'),
(73, 'Makeup', 'MF014', 'Blusher', 'Too Faced Peach My Cheeks Melting Powder Blush', 'http://ohmystellar.com/wp-content/uploads/2018/10/IMG_8357.jpg', 550000, '', 550000, '  Cho đôi má ửng hồng với mùi đào ngọt nhẹ thư giãn, đây được xem là dòng má hồng được yêu thích nhất của hãng khi sở hữu bảng màu má phong phú, thời thượng dễ dùng.\r\n  Sở hữu chất phấn siêu mịn, Má Hồng Too Faced lên màu cực kì chuẩn, dễ blend tạo hiệu ứng ưng ý nhất cùng độ bám siêu lì, cho bạn tự tin suốt cả ngày. Thành phần lành tính, an toàn với mọi loại da kể cả da nhạy cảm cùng hương thơm đào dễ chịu'),
(74, 'Makeup', 'MF015', 'Blusher', 'Bonjours Cream Blush Healthy Glow', 'https://i.pinimg.com/originals/55/0b/cb/550bcb150769152fc6ad24b568dba1f4.jpg', 355000, '', 355000, 'Không chỉ riêng thiết kế của phấn má Chanel Le Blush Crème mà mọi dòng sản phẩm của mỹ phẩm Chanel vẫn luôn rất đơn giản, gọn nhẹ và toát lên một vẻ sang trọng đẳng cấp cao. Hộp phấn được làm từ nhựa nên khi cầm sẽ cảm thấy gọn nhẹ và rất chắc tay. Bao phủ cả hộp phấn là tông đen huyền bí cùng với logo màu trắng chữ x được lồng trong vòng tròn của hãng, bật lên cảm giác tinh tế, sang trọng và lôi cuốn. Bên trong hộp phấn còn có trang bị một gương nhỏ vừa đủ giúp bạn make up rất tiện lợi mọi lúc mọi nơi. Một hộp phấn má hồng Chanel màu 82 thường đi kèm với một túi nhung nhỏ để bảo vệ chống trày hộp nhựa của hãng. Tuy nhiên, chất liệu nhung này rất dễ bám bụi và bẩn.'),
(75, 'Makeup', 'ML001', 'Lips', 'Son Glossier Generation G', 'https://img.makeupalley.com/2/9/0/5/2948356.JPG', 540000, '', 540000, 'Generation G là một loại màu son mới mang lại vẻ ngoài và độ hoàn thiện của son môi không bị lem, không bị lem. Chúng tôi đã tạo ra một danh sách ngắn gồm sáu sắc thái quan trọng nhất, với các sắc tố được quay xuống cho một cái nhìn bình thường. Những thỏi son của họ thích nghi với bạn, không phải theo cách khác, vì vậy chúng sẽ xuất hiện một chút khác biệt với mọi người khi màu môi tự nhiên của bạn thể hiện qua. Tác dụng? Khuếch tán, tốt đẹp mờ chỉ cần vuốt nó lên.'),
(76, 'Makeup', 'ML002', 'Lips', 'Son Coulorpop LUX Lipstick', 'https://mint07.com/wp-content/uploads/2018/08/son-colourpop-lux-lipstick-foolish12.jpg', 240000, '', 240000, 'Son ColourPop Lux Lipstick được cải tiến vượt bậc không chỉ về thiết kế mà còn cả chất son. Chất son mềm mịn nhờ những thành phần chính giàu dưỡng chất sau:\r\nShea Butter (bơ hạt mỡ,&nbsp;Palm Butter (bơ dầu cọ), Jojoba Seed Oil (dầu Jojoba), Hydrogenated Vegetable Oil,&nbsp;Punica Granatum Seed Oil: tinh dầu tự nhiên giúp dưỡng môi mềm mượt, không bị khô khi dùng son cả ngày.Chất tạo màu:&nbsp;Blue 1 Lake (CI 42090), Iron Oxides (CI 77492, CI 77499), Titanium Dioxide (CI 77891).\r\n'),
(77, 'Makeup', 'ML003', 'Lips', 'Son 3CE Matte Lip Color New Version', 'https://bizweb.dktcdn.net/100/318/204/products/3ce-matte-lip-color-bici-cosmetics21.jpg?v=1550741977850', 399000, '', 399000, '- 3CE Matte Lip Color New Version gồm 3 tông màu vô cùng thời thượng đem đến cho bạn một phong cách trẻ trung, năng động.\r\n\r\n- Cây son này sẽ không khiến các bạn nữ thất vọng bởi độ mềm mượt vì đôi môi của chúng ta được cấp ẩm tối ưu. Vậy nên các bạn cũng không cần lo lắng về hiện tượng rãnh ở môi nhé.\r\n\r\n- Thiết kế mới vô cùng “sang chảnh” và đẳng cấp của 3CE sẽ đốn tin các fan nữ bởi son môi không chỉ là để trang điểm mà còn là món trang sức quý giá của các bạn nữ.'),
(78, 'Makeup', 'ML004', 'Lips', '', 'https://cdn.shopify.com/s/files/1/1338/0845/products/Snowfleek_a_800x1200.jpg?v=1529969567', 539000, '', 539000, 'Về độ bám màu, dòng  son Colourpop Ultra Matte Lip của Colourpop thực sự khiến khách phải “tâm phục khẩu phục” bởi độ mịn siêu lì của dòng son mới này. Son có thể giữ lâu trong ngày nếu như không ăn uống nhiều.\r\n\r\nBảng màu son lên đến 42 màu  đa dạng và phù hợp với mọi trường hợp, mọi làn da, bạn sẽ dễ dàng tìm được một thỏi phù hợp ngay cho mình phải không nào… Sản phẩm này cũng đã được beauty blogger ChangMakeup swatch trên môi khá rõ ràng và chi tiết giúp  cho những bạn còn lăn tăn về chất son khi đánh lên môi, hay khả năng tán đều, tạo hiệu ứng đầy đăn khi đánh full môi đều được  thể hiện sắc nét.'),
(79, 'Makeup', 'ML005', 'Lips', 'Son Marc Jacobs New Nude Sheer Gel Lipstick', 'https://www.marcjacobsbeauty.com/dw/image/v2/AAXW_PRD/on/demandware.static/-/Sites-itemmaster_MJB/default/dwa81cbaff/hi-res/MJ40006_MJ4140.jpg?sw=550', 730000, '', 730000, 'Về độ bám màu, dòng  son Colourpop Ultra Matte Lip của Colourpop thực sự khiến khách phải “tâm phục khẩu phục” bởi độ mịn siêu lì của dòng son mới này. Son có thể giữ lâu trong ngày nếu như không ăn uống nhiều.\r\n\r\nBảng màu son lên đến 42 màu  đa dạng và phù hợp với mọi trường hợp, mọi làn da, bạn sẽ dễ dàng tìm được một thỏi phù hợp ngay cho mình phải không nào… Sản phẩm này cũng đã được beauty blogger ChangMakeup swatch trên môi khá rõ ràng và chi tiết giúp  cho những bạn còn lăn tăn về chất son khi đánh lên môi, hay khả năng tán đều, tạo hiệu ứng đầy đặn khi đánh full môi đều được  thể hiện sắc nét.'),
(80, 'Makeup', 'ML006', 'Lips', 'Son Too Faced Peach Kiss Moisture Matte Long Wear Lipstick ', 'https://s3.r29static.com//bin/entry/dbf/x,80/1832674/image.jpg', 520000, '', 520000, 'Thân son được đập chìm hình ảnh quả đào, hứa hẹn sẽ làm tan chảy trái tim của những cô nàng kẹo ngọt.\r\n\r\nChất son matte mịn mượt, được ứng dụng công nghệ độc quyền Comfort Matte Technology ™ giúp lớp son lì bám chắc vào môi nhưng không gây cảm giác nặng môi, không làm khô môi.\r\n\r\nSon có độ bám màu tốt lên đến 8 tiếng. Khi apply lên môi, các nàng sẽ cảm nhận được mùi hương đào ngọt dịu, thoang thoảng vô cùng gây nghiện.'),
(81, 'Makeup', 'ML007', 'Lips', 'Son Dior Addict Lip Glow 004 Coral', 'https://m.sephora.ae/catalog/product/cache/1/image/1800x/040ec09b1e35df139433887a97daa66f/d/i/dior_addic-dior-f002875535_main_3.jpg', 874000, '', 874000, 'Dior Addict Lip Glow: \"Công chúa\" của thế giới son dưỡng\r\nSon dưỡng Dior có màu tươi hồng rất tự nhiên, độ bóng vừa phải, che được rãnh nứt và các vết khô ráp trên môi. Vì thế, chỉ cần một lớp son dưỡng Dior, đôi môi nhợt nhạt của bạn sẽ hồng hào đầy sức sống ngay lập tức. Chỉ số chống nắng SPF10 giúp bảo vệ đôi môi bạn. Các thành phần bơ xoài và chiết xuất xơ mướp dưỡng ẩm, mang lại cho bạn đôi môi gợi cảm.'),
(82, 'Makeup', 'ML008', 'Lips', 'Son Charlotte Tilbury MATTE REVOLUTION Red Carpet Red', 'http://oanhstore.com/uploads/son-Charlotte-Tilbury-Matte-Revolution-Red-Carpet-swatch-review-1-510x596.jpg', 857000, '', 857000, 'Son Charlotte Tilbury Matte Revolution có bảng màu siêu chất với dải màu son tuyệt đẹp, chủ yếu là những màu son hot trend bậc nhất thế giới, làm nên những “cuộc cách mạng” về xu hướng son lì, y như tên gọi của nó – Matte Revolution. Dấu ấn son Charlotte Tilbury Glastonberry Son Charlotte Tilbury Glastonberry vỏ vàng sang trọng Cầm trên tay Charlotte Tilbury Matte Revolution Glastonberry, các cô nàng không khỏi xao xuyến vì thỏi son đẹp tới ngỡ ngàng. Lớp vỏ ngoài của son được mạ vàng với những đường gân chạy dọc thân son làm toát lên vẻ sang trọng và đẳng cấp khác biệt. Một nét đẹp hoà trộn giữa hiện đại và cổ điển, là định nghĩa hoàn hảo của thỏi son môi trong mơ của phái đẹp.'),
(83, 'Makeup', 'ML009', 'Lips', 'Son Tom Ford Boys & Girls Lip Color - Evan', 'https://bergdorfgoodman.scene7.com/is/image/bergdorfgoodman/BGC4T2T_9Q_m?&wid=400&height=500', 836000, '', 836000, 'Torm Ford giới thiệu 50 cô gái cho bộ sưu tập Lips & Boys. Mỗi thỏi son được đặt theo tên của các cô gái, từ các mối liên hệ với các đồng nghiệp từ khắp nơi trên thế giới. Được thiết kế để dùng riêng biệt hoặc dùng chung với nhau, mỗi sự biến đổi về màu sắc và chất son thể hiện tính cách riêng của mỗi cô gái và chàng trai. Sắc tố màu đặc biệt được tán đều, truyền màu son tinh khiết nhất vào chất son, để có lớp son matte, cream và metallic.\r\n'),
(84, 'Makeup', 'ML010', 'Lips', 'Son Innisfree Vivid Cotton Ink 4g - 10 Brown Tea Tulip', 'https://upload.lixibox.com/system/pictures/files/000/038/714/large/1550481811.png', 177000, '', 177000, 'Son Tint Lì Mềm Mượt Innisfree Vivid Cotton Ink (4g) với chất son mềm mượt chuyển dần sang chất lì nhưng vẫn nhẹ môi, mịn mượt\r\nSự kết hợp giữa 4 tinh dầu: hạt xoài, bơ, camellia, hạt bông tạo hiệu ứng lì giúp lớp màu giữ bền lâu trên môi.\r\nSản phẩm thiết kế đẹp mắt, vừa tay cầm, có nhiều màu sắc để lựa chọn.'),
(85, 'Makeup', 'ML011', 'DM', 'Gel Tẩy Tế Bào Chết Dưỡng Ẩm Môi Innisfree Lip Peeling Booster', 'https://www.kosmebox.com/image/cache/data/INNISFREE/gel-tay-te-bao-chet-duong-am-moi-innisfree-lip-filling-booster.html/gel-tay-te-bao-chet-duong-am-moi-innisfree-lip-filling-booster.html-500x500.JPG', 150000, 's', 120000, '- Innisfree Lip Peeling Booster có thành phần tự các dược liệu tự nhiên như trà xanh, dầu hạt macadamia và dầu hạt hướng dương giúp bạn lấy đi các lớp tế bào chết một cách dễ dàng, làm sạch môi.\r\n\r\n- Có tác dụng dưỡng ẩm môi hiệu quả, chống khô nứt môi. Với những bạn đang gặp phải tình trạng khô môi, bong tróc da môi thì đây sẽ là sản phẩm hiệu quả trong việc dưỡng ẩm, chống khô môi.\r\n\r\n- Có khả năng làm sạch môi từ đó giúp bước trang điểm môi dễ dàng, màu son sẽ lên đều và rõ nét hơn.\r\n\r\n- Trong gel chứa các hạt massage siêu nhỏ giúp lưu thông máu làm cho môi bạn hồng hào.\r\n\r\n- Với thành phần được chiết xuất từ tự nhiên, lành tính tuyệt đối an toàn và phù hợp với mọi loại da.'),
(86, 'Makeup', 'ML012', 'DM', 'Mặt Nạ Ngủ Dưỡng Ẩm Môi Và Phục Hồi Môi Thâm Laneige Lip Sleeping Mask (Berry)', 'https://www.kosmebox.com/image/cache/data/BIGDEAL/Laneige-Lip-Sleeping-Mask-7-500x500.JPG', 329000, '', 329000, 'Về tính chất, sản phẩm là mặt nạ ngủ dành riêng cho môi giúp các tế bào chết bong tróc được hòa tan và làm sạch một cách nhẹ nhàng trong đêm và giúp cho đôi môi bạn luôn căng đầy sức sống.\r\n\r\nCông dụng sản phẩm:\r\n\r\nSự kết hợp giữ các quả mọng như Raspberry (quả mâm xôi), Blueberry (Việt quất), Strawberry (Dâu tây), Cranberry (Nam việt quất), Gojiberry, Soapberry, Cloudberry \r\n\r\n'),
(87, 'Makeup', 'ML013', 'DM', 'Son Dưỡng 2 Tone Màu Laneige Two Tone Matte Lip Bar', 'https://www.kosmebox.com/image/cache/data/Laneige/son-li-2-tone-mau-laneige-two-tone-matte-lip-bar.html/son-li-2-tone-mau-laneige-two-tone-matte-lip-bar%20(1)-500x500.jpg', 400000, '', 400000, 'Son Lì 2 Tone Màu Laneige Two Tone Matte Lip Bar với chất son matte mịn như nhung, lướt nhẹ trên môi, lên màu cực chuẩn ngay lần đầu. Độ lên màu chuẩn, chất son matte cực mịn nhẹ trên môi bám màu cực tốt tạo nên lớp son mịn lì suốt thời gian dài nhưng không hề gây khô, hay lộ nhiều vân môi. Đây thật sự là \"bảo bối\" cho cô nàng có làn môi khô thiếu ẩm nhưng đã lỡ \"say đắm\" những dòng son lì.'),
(88, 'Makeup', 'ML014', 'DM', 'Son Dưỡng Môi Tonymoly Kiss Kiss Lip Essence Balm SPF15++/PA 7g', 'https://www.kosmebox.com/image/cache/data/ReplaceImages/TONYCC12-500x500.jpg', 90000, '', 90000, 'Công dụng: \r\n\r\n- Son dưỡng môi cho làn môi mềm mại, không bị khô hay nứt nẻ, dưỡng ẩm đôi môi suốt ngày dài.\r\n\r\n- So với các loại son dưỡng thông thường, sản phẩm dạng kem có khả năng chống nắng SPF15, tránh những tác động của tia tử ngoại lên môi.\r\n\r\n- Với công thức tuyệt vời giúp dễ dàng thoa lên đôi môi mà còn không gây cảm giác nhờn khó chịu.'),
(89, 'Makeup', 'ML015', 'DM', 'Tẩy Tế Bào Chết Và Giảm Thâm Môi The Face Shop Lip Scrub Shea Butter 10g', 'https://www.kosmebox.com/image/cache/data/ReplaceImages/FSCC87-500x500.jpg', 110000, '', 110000, 'Lip Scrub Shea Butter giúp bạn nhẹ nhàng tẩy đi lớp tế bào chết cho môi, song song với quá trình cung cấp các dưỡng chất dưỡng ẩm cho làn môi của bạn, không những giúp hạn chế tình trạng thâm, tối màu, mà còn trở nên mềm mịn và căng tràn sức sống hơn.'),
(90, 'Makeup', 'ME001', 'Eyes', 'Chì Kẻ Mày Chanel Crayon Sourcil Scrupting Eyebrow Pencil', 'https://cdn.influenster.com/media/product/image/30_-_BRUN_NATUREL.jpg.750x750_q85ss0_progressive.jpg', 500000, '', 500000, 'Chì kẻ mày dạng vặn Chanel Stylo Sourcils Waterproof với đầu chì ngang dẹp giúp định hình chân mày dễ dàng.\r\n- Kết cấu dạng sáp kem dễ tán, không gây bợn cùng màu sắc tự nhiên cho bạn nét mày hiện đại, trẻ trung. Chì mày dạng vặn tiện lợi, không cần chuốt.\r\n- Thiết kế 2 đầu độc đáo: 1 đầu là chì tán chân mày thiết kế đầu dẹt vặn lên, đầu kia là chổi chải chân mày.\r\n- Đầu chì sáp sắc sảo giúp tạo nét chân mày tinh tế, đầu bột với công thức chứa silicon & khoáng chất giúp tán đều và giữ màu lâu trôi suốt 12 giờ'),
(91, 'Makeup', 'ME002', 'Eyes', 'Chì Kẻ Chân Mày Mảnh Innisfree Skinny Brow Pencil 0.08G', 'https://salt.tikicdn.com/cache/w1200/ts/product/c9/80/2b/f7385bf3e2db7f1afe176aa34a75b095.JPG', 170000, '', 170000, 'Chì Kẻ Chân Mày Mảnh Innisfree Skinny Brow Pencil 0.08G Giúp trang điểm chân mày tự nhiên.\r\nĐộ lên màu chuẩn\r\nLâu trôi\r\nHướng dẫn sử dụng:\r\nVẽ khung chân mày.\r\nTô phần bên trong chân mày. Dùng cọ chải đều theo hướng lông mày để trông tự nhiên.');
INSERT INTO `products` (`id`, `catalogue`, `msp`, `type`, `product_name`, `product_img`, `price`, `sale`, `product_price`, `product_description`) VALUES
(92, 'Makeup', 'ME003', 'Eyes', 'Chì Kẻ Mày Brook S- Brow Lift Charlotte Tilbury', 'https://images.ctfassets.net/wlke2cbybljx/3Z0uEUXdlTq1lJ54ko71zb/c052a0644ba7ab847a2ff9933d5e36ed/Brook-S-Lid-Off-Shade-Packshot.png?w=500&h=500&fit=fill&fm=jpg&bg=rgb%3Afbfafa', 355000, '', 355000, 'Sản phẩm kẻ chân mày Charlotte Tilbury Brow Lift Rita với thiết kế hai đầu tương tự các sản phẩm chì kẻ mày khác. Nhưng lại được yêu thích đặc biệt vì đầu chì mềm mịn dễ kẻ. Màu sắc tự nhiên giúp bạn có hàng chân mày đầy đặn.'),
(93, 'Makeup', 'ME004', 'Eyes', 'Chì Kẻ Mày Nars Brow Perfector', 'https://www.narscosmetics.com/dw/image/v2/BBSK_PRD/on/demandware.static/-/Sites-itemmaster_NARS/default/dw372e6d2e/hi-res/0607845011330.jpg?sw=856&sh=750&sm=fit', 465000, '', 465000, 'Chì kẻ chân mày Nars Brow Perfector có thể làm hài lòng mọi cô nàng khó tính. Với thiết kế hai đầu, một đầu chì với cấu trước mềm mướt dễ dàng lướt tạo và kẻ lông mày. Đầu còn lại là chổi mềm, giúp khếch tán chì tạo độ tự nhiên cho lông mày.'),
(94, 'Makeup', 'ME005', 'Eyes', 'Chì Kẻ Mày NYX Micro Brow Pencil', 'https://www.nyxcosmetics.ca/dw/image/v2/AATL_PRD/on/demandware.static/-/Sites-nyx-master-catalog/default/dw8a2be9eb/ProductImages/Eyes/Micro_Brow_Pencil/800897836702_microbrowpencil_taupe_main.jpg?sw=600&sh=600&sm=fit&q=70', 310000, '', 310000, 'Đầu chì siêu nhỏ NYX MICRO BROW PENCIL giúp bạn dễ dàng lấp đầy những khoảng trống trên lông mày mà vẫn cho kết quả tự nhiên. Khi bạn tận dụng tối đa cả đầu cọ còn lại để tán đều thì hàng mày của bạn sẽ trông như đẹp sẵn vậy.'),
(95, 'Makeup', 'ME006', 'Mas', 'Mascara tạo độ cong và dày mi tự nhiên Innisfree Skinny Volumecara 3.5g - Đen', 'https://kutegiagoc.com/wp-content/uploads/2018/08/Chuot-mi-Innisfree-Skinny-Volumecara-Mascara.png', 230000, '', 230000, 'Nếu bạn yêu thích phong cách trang điểm trong trẻo của Hàn Quốc với hàng mi dày, cong nhẹ nhàng, nữ tính thì đây sẽ là lựa chọn tuyệt vời cho bạn. Đầu tiên phải kể đến chất mascara có khả năng giữ lông mi cong suốt cả ngày. Bạn sẽ không phải lo lắng khi đến cuối ngày lông mi lại trở nên thẳng đuột và lúc nhắm mắt có thể để lại vệt đen xuống bầu mắt dưới.\r\n\r\nPhần lược chải được làm tối giản hình tam giác với phần lông xen kẽ zic zac, giúp dễ dàng chuốt từ gốc mi trở ra và đặc biệt là chuốt cho phần mi ở mí mắt dưới dày hơn. Mascara còn có hai màu đen và nâu cho bạn nhiều lựa chọn. Màu nâu sẽ tạo cảm giác đôi mắt trông to tròn và long lanh hơn nữa đấy.'),
(96, 'Makeup', 'ME007', 'Mas', 'Mascara Chải Mi A\'Pieu Skinny Dual Mascara 3g/3.5g', 'https://salt.tikicdn.com/cache/w1200/ts/product/92/a5/d8/cbfbdeadf542ebaead52425e0b0f12fd.jpg', 325000, '', 325000, 'Mascara Chải Mi A\'Pieu Skinny Dual Mascara 3g/3.5g là dòng mascara tích hợp 2 trong 1 vừa có tác dụng tăng độ dài của mi vừa có tác dụng làm cong mi. Thiết kế 2 đầu với 2 dạng cọ khác nhau giúp phát huy tối đa công năng của cọ. Đầu cọ làm dài mi thiết kế dạng xoắn ốc, tiếp xúc dễ dàng với các sợi mi ngắn nhất đảm bảo mi dài đều tự nhiên. Đầu cọ làm cong mi thì có thiết kế siêu mảnh, gia tăng diện tích tiếp xúc sâu tới chân mi giúp uốn cong tối đa.\r\n2 đầu cọ chứa 2 dưỡng chất riêng biệt, thân mascara nhỏ gọn bao bọc trong thân nhám màu đen xám sang trọng. Bạn có thể dễ dàng mang theo bên mình bất cứ đâu để chau chuốt cho làn mi mình.\r\nƯu điểm của sản phẩm không thể bỏ qua đó chính là khả năng chống trôi \"water-proof\". Khi tham gia các hoạt động ngoài trời, đổ mồ hôi, gặp nước làn mi của bạn vẫn giữ nguyên độ cong và dài quyến rũ.'),
(97, 'Makeup', 'ME008', 'Mas', 'Mascara Maybelline Làm Dài Và Cong Mi Hyper Curl 9.2ml', 'https://salt.tikicdn.com/cache/w1200/ts/product/9e/4e/49/45844d8c0540ab44a2abf76a639c75cf.jpg', 135000, '', 135000, '- Mascara phù hợp với hàng mi mỏng, thưa và không được dài. Nhờ công thức tối ưu kết hợp với đầu cọ được thiết kế dễ dàng chải tận gốc sợi mi, giúp mascara được bao phủ hiệu quả.\r\n- Công thức trong mỹ phẩm Maybelline không thấm nước, không lem trong nước, trong môi trường ẩm hay da dầu.'),
(98, 'Makeup', 'ME009', 'Mas', 'Mascara Maybelline Magnum Làm Dày Mi 10 Lần (9.2ml)', 'https://salt.tikicdn.com/cache/550x550/ts/product/49/e8/ac/fb59b69db60ac72f9bc610c8607069d9.jpg', 175000, '', 175000, 'Mascara Maybelline Magnum là sản phẩm có công thức vượt trội, với đầu cọ cải tiến, cho mi dày gấp 10 lần.\r\nMascara làm dày mi Magnum Maybelline với thiết kế đầu cọ to, hơi cong và các sợi lông cọ mảnh dài xếp đều giúp sản phẩm khi chuốt mi có thể chạm đến sợi mi ngắn nhất, giúp tách rời và chuốt đều từng sợi mi. Hàng mi rợp và dày hơn gấp 10 lần bình thường.\r\nMascara làm dày mi Magnum là dòng sản phẩm không thấm nước, chống trôi và hạn chế lem mascara kể cả trong môi trường nước hay dầu.\r\nCollagen trong Mascara giúp dưỡng và ngăn rụng mi hiệu quả.'),
(99, 'Makeup', 'ME010', 'Mas', 'Mascara Anastasia Beverly Hills Drip Brown', 'https://www.anastasiabeverlyhills.com/dw/image/v2/BBLL_PRD/on/demandware.static/-/Sites-anastasia-master-catalog/default/dwa26c0b6b/images/products/2019/030419_SpringLaunch/DarkBrown_main.jpg?sw=1376&sh=1376&sm=fit', 360000, '', 360000, 'Thích hợp với bạn nào sợ kẻ chân mày bị lố tay, quá dừ. Em này là gel trong suốt để giữ cố định lông mày, cho bạn hàng chân mày vào nếp, ngay ngắn gọn gàng \r\n\r\nAnastasia thì món nào cho chân mày, highlight cũng đỉnh cao rồi nên không dám lạm bàn chất lượng, giới thiệu phù hợp với đối tượng nào thôi.'),
(100, 'Makeup', 'ME011', 'EP', 'Bảng Phấn Mắt ColourPop Yes, Please', 'https://cdn.shopify.com/s/files/1/1338/0845/collections/Category-Eyes-Shadow_Palette_970d8d30-44d4-4cba-81ad-68625e40dce0_1024x.jpg?v=1557962638', 450000, '', 450000, '1. de9f7d : Nâu nude\r\n2. cb795e : Nâu đỏ\r\n3. b06e55 : Nâu đậm\r\n4. d88878 : Hồng nude\r\n5. f07e62 : Cam đào\r\n6. c86c60 : Hồng nude đậm\r\n7. a65130 : Nâu đỏ đậm\r\n8. b95446 : Hồng nâu\r\n9. 743d2d : Đỏ nâu'),
(101, 'Makeup', 'ME012', 'EP', 'Bảng Phấn Mắt 9 Màu Peach C Soft Mood Eyeshadow Palette', 'http://product.hstatic.net/1000006063/product/018000000030_1e855e1b2eed4ee2b2c6224797db0525_grande.jpg', 370000, '', 370000, 'Bảng Phấn Mắt 9 Màu Peach C Soft Mood Eyeshadow Palette\r\n\r\n- Thương hiệu: Peach C\r\n\r\n- Gồm 9 tone màu :\r\n\r\n1. de9f7d : Nâu nude\r\n2. cb795e : Nâu đỏ\r\n3. b06e55 : Nâu đậm\r\n4. d88878 : Hồng nude\r\n5. f07e62 : Cam đào\r\n6. c86c60 : Hồng nude đậm\r\n7. a65130 : Nâu đỏ đậm\r\n8. b95446 : Hồng nâu\r\n9. 743d2d : Đỏ nâu'),
(102, 'Makeup', 'ME013', 'EP', 'Bảng Mắt Trang Điểm CLIO PRO EYE PALETTE CLIO PRO EYE PALETTE 03 CORAL TALK', 'https://h4d9p8u9.stackpathcdn.com/media/catalog/product/cache/926507dc7f93631a094422215b778fe0/m/_/m_u-m_t-trang-_i_m-clio-pro-eye-palette-03-corall-talk-3_1.png', 895000, '', 895000, 'Màu mắt dạng bột, dễ tán đều trên bề mặt da, tạo cảm giác mỏng nhẹ, đồng thời có độ bám dính tốt, các hạt kim tuyến không bị rơi rớt xung quanh. Khả năng phản chiết ánh sáng tốt, cho đôi mắt lung linh tỏa sáng. Đôi mắt được makeup với phong cách “ươn ướt” sẽ khiến gương mặt bạn trẻ trung, tươi sáng hơn.\r\n\r\nCọ thiết kế dạng lông 2 đầu (1 size trung, 1 size nhỏ) và cọ chất lông cực đẹp.'),
(103, 'Makeup', 'ME014', 'EP', '', 'https://cdn.shopify.com/s/files/1/0016/8794/5275/products/3ce-mood-recipe-multi-eye-color-palette-overtake-002_1200x1200.jpg?v=1540772293', 750000, '', 750000, 'Hướng dẫn sử dụng Bảng phấn mắt 3ce 9 ô:\r\n\r\n- Dùng cọ lấy phấn một cách nhẹ nhàng, tránh để phấn dây ra xung quanh hộp\r\n\r\n- Không nên dùng ngón tay để quẹt phấn\r\n\r\n- Nếu yêu thích phong cách trang điểm trẻ trung tự nhiên, hãy chọn nhiều phấn cam nude;\r\n\r\n- Nếu yêu thích phong cách trang điểm cá tính với mắt khói, hãy chọn nhiều phấn nâu đồng.'),
(104, 'Hair', 'H001', 'NT', 'Thuốc Nhuộm Tóc L’oreal ', 'http://cuahangmypham.vn/public/media/media/thumb/03/0060231_l.jpg', 250000, '', 250000, 'Thuốc Nhuộm Tóc L’oreal Excellence Creme Advanced Triple Care Colour này là dạng kem bọt, có chiết xuất từ những thành phần an toàn không chỉ bảo vệ tóc tránh hư tổn mà còn mang đến mái tóc đều màu, bóng mượt, mềm mại và khỏe mạnh ngay cả sau khi nhuộm.\r\nĐặc biệt bạn còn được dịp trổ tài “sì-pa” cho mái tóc ngay tại gia với khả năng lên màu “chuẩn không cần chỉnh” nhờ những đặc điểm nổi trội sau:\r\n– Dưỡng chất Pro-keratin: tăng cường chất sừng của tóc, bảo vệ và phục hồi cho mái tóc chắc khỏe.\r\n– Ceramide: bảo vệ và làm mượt tóc.\r\n– Collagen: nuôi dưỡng và trẻ hóa cho mái tóc dày hơn.'),
(105, 'Hair', 'H002', 'NT', 'Thuốc Nhuộm Phủ Bạc Revlon Topspeed', 'https://vn-test-11.slatic.net/p/5/thuoc-nhuom-toc-revlon-colorsilk-47-medium-rich-brown-5112-5699192-0af81bfd4cd95fba5271525b52a59584-catalog.jpg_340x340q80.jpg_.webp', 160000, '', 160000, ''),
(106, 'Hair', 'H003', 'NT', 'Lược Nhuộm Tóc Thông Minh Just 1 Minute Hàn Quốc', 'https://luocthongminh.com/upload/images/tin-tuc/luoc-nhuom-toc-thong-minh-han-quoc.jpg', 520000, '', 520000, '- Lược Nhuộm Tóc Thông Minh Just 1 Minute Hàn Quốc là sản phẩm công nghệ tiên tiến hàng đầu chỉ cần thao tác rất đơn giản để thực hiện việc nhuộm tóc ngay tại nhà một cách an toàn và hiệu quả.\r\n- Lược nhuộm tóc thông minh có phần chốt cài lược vào lõi thuốc thiết kế thông minh giúp người dùng dễ dàng lắp và tháo lược vào lõi nhuộm\r\n- Chất liệu nhựa PP nguyên sinh an toàn cho sức khỏe'),
(107, 'Hair', 'H004', 'NT', 'Thuốc nhuộm phủ bóng Elumen Goldwell', 'https://cf.shopee.vn/file/91993f1933a4c7d928b4805c1166f10d', 450000, '', 450000, '- Elumen còn có khả năng chữa trị hồi phục các mái tóc hư tổn Mái tóc sau khi nhuộm sẽ trở nên bóng sáng và khỏe mạnh\r\n- Nhờ lực hút tĩnh điện các hạt màu mang điện tích âm bị hút sâu vào trong lõi tóc Không ammoniac không phản ứng hóa học nên loại màu nhuộm này không làm mở các lớp biểu bì tóc không thay đổi cấu trúc và không gây hại cho tóc Đặc biệt với độ pH 3 tương tự như của các sản phẩm dưỡng tóc màu nhuộm'),
(108, 'Hair', 'H005', 'NT', 'Thuốc nhuộm tóc Kadus ', 'https://www.sendo.vn/nhip-song/media/camnang/2017/06/thuoc-nhuom-toc-tot-Kadus.jpg', 450000, '', 450000, 'Màu tóc vĩnh viễn này là một kem đầy đủ thêm. Các sắc tố màu trong thuốc nhuộm tóc thấm sâu vào tóc. Thuốc nhuộm tóc cung cấp 100% màu xám. Sản phẩm này rất kinh tế để sử dụng và có sẵn trong 80 màu sắc khác nhau. Thuốc nhuộm tóc: \r\n- Có sắc tố màu thấm sâu vào tóc\r\n- Là kinh tế để sử dụng\r\n- Cung cấp 100% màu xám\r\n- Có sẵn trong 80 màu sắc khác nhau\r\n- Hoạt động tối ưu với Kadus vĩnh viễn Hydrogen'),
(109, 'Hair', 'H006', 'UT', 'Tinh Chất Dưỡng Tóc Miseen Scène Perfect Repair Hair Serum', 'https://product.hstatic.net/1000230992/product/mjsen_002_light-500x500_1024x1024.jpg', 140000, '', 140000, 'Serum Miseen Scène Perfect Repair Hair Serum đã có mặt tại hệ thống mỹ phẩm chính hãng Beauty Garden với thành phần chính đến từ sữa ong chúa:\r\n- Dưỡng chất đến từ hạt argan gồm các chất dinh dưỡng, vitamin, axit béo, axit ferulic, tám axit béo thiết yếu, carotenoids, chất chống oxy hóa, sterol, saponin và polyphones cần thiết cho tóc của bạn; Đặc biệt giầu Vitamin E, thành phần chống oxy hóa, táo tạo và cung cấp dưỡng chất cho tóc khô.\r\n- Dưỡng chất nhờ sữa ong chúa cho tóc: Sữa ong chúa có chứa 22 các axit amin,cung cấp các chất cần thiết cho từng lọn tóc. Giúp “sửa chữa” những tế bào da bị tổn thương do hóa chất, tia xạ, tia cực tím gây ra, lấp đầy những lỗ đứt gẫy trên sợi tóc bạn.'),
(110, 'Hair', 'H007', 'UT', 'Kem ủ tóc Garnier Fructis ', 'http://scontent.webpluscnd.net/photos-df/a-0/8246-1902826-1/kem-u-toc-garnier-fructis-oil-repair-3-wunderbutter-400-ml.png?atk=9a9c3ea59a8da91d948b2238d8c1f6a4', 210000, '', 210000, 'Chiết xuất từ trái bơ Địa Trung Hải và các loại hoa quả đặc trưng của Châu Âu là loại kem ủ tóc rất được ưa chuộng tại thị trường Âu Mỹ do xu hướng sử dụng mỹ phẩm thiên nhiên và sự nổi tiếng của thương hiệu Garnier: \r\n- Nguồn gốc thiên nhiên cho công dụng dưỡng tóc vượt trội.\r\n-  Không chứa chất bảo quản, rất lành tính cho tóc.\r\n-  Kem ủ/hấp giúp tóc mềm mượt nhờ tác động nhẹ nhàng từ tinh chất trái bơ giàu vitamin A,E, thơm nhẹ, bóng tóc.\r\n- Kem ủ tóc Garnier phù hợp với tất cả các loại tóc, không gây kích ứng da đầu nhờ thành phần thiên nhiên. '),
(111, 'Hair', 'H008', 'UT', 'KEM Ủ TÓC LOREAL ELSEVE FRANCE', 'https://truonganmart.vn/images/hanghoa/bu-toc-l-ore-al-elseve-arginine-resist-300ml.jpg', 230000, '', 230000, '- Kem ủ tóc L\'oreal Elseve Arginine Resist X3: cung cấp dưỡng chất cần thiết từ gốc mà không gây nhờn cho da đầu. Bước tiếp theo trong quá trình củng cố và phục hồi mái tóc, Protein được cung cấp sẽ giúp nuôi dưỡng tóc từ gốc đến ngọn. Chính vì lẽ đó, đây còn là sản phẩm được khuyên dùng với những bà mẹ bị chứng rụng tóc sau sinh. Không chỉ giúp tóc chắc khỏe hơn, kem ủ tóc L\'oreal Elseve Arginine Resist X3 còn giảm tối đa sự rụng tóc.\r\n- Kem ủ tóc LOreal Phục hồi cấu trúc tóc bị tổn thương, cung cấp dinh dưỡng cho tóc, mang lại sức mạnh chống chịu cho tóc gấp 3 lần, nuôi dưỡng tóc từ gốc đến ngọn giúp tóc mượt mà và khỏe mạnh, đầy lùi 5 dấu hiệu hư tổn: gãy, khô, yếu, thô và chẻ ngọn. Hoạt chất trong kem ủ tóc LOreal Elseve nhanh chóng hấp thu vào các vùng tóc yếu, giúp tóc khỏe và tăng độ đàn hồi, tăng cường dưỡng ẩm cho tóc suôn mềm, bóng mượt và không bị chẻ ngọn.'),
(112, 'Hair', 'H009', 'UT', 'KEM ủ tóc Azona', 'http://dndsalon.com/app/css/images/products/1489156754d5d7ade3662de05192dfb2.jpg', 320000, '', 320000, '- Kem ủ tóc cao cấp Azona Collagen là sự kết hợp tuyệt vời công nghệ nano trong việc chiếc xuất tinh chất từ thảo dược thiên nhiên tạo ra hợp chất siêu dưỡng Protein có tác dụng trong việc phục hồi, hồi sinh lại những mái tóc bị hư tổn, giúp tái tạo cấu trúc lõi tóc cơ bản tạo sự đàn hồi cho tóc trong quá trình uốn duỗi nhuộm\r\n- Kem ủ Azona Collagen giúp bảo vệ quá trình tác nhân gây nhiệt như kẹp, sấy chải nhiệt, bảo vệ màu tóc dưới ánh nắng mặt trời, cung cấp độ ẩm và dưỡng chất cần thiết giúp tóc mềm mại óng mượt. Nuôi dưỡng và phục hồi tóc từ trong ra ngoài.\r\n\r\n'),
(113, 'Hair', 'H010', 'UT', 'Kem ủ tóc Beaua 10 tinh chất', 'http://static.minicare.vn/9429/product/2019/01/16/kem-u-toc-beauau-10-1547625567.jpg', 250000, '', 250000, '- Kem ủ tóc tinh chất chiết xuất từ 10 loại thảo dược giúp tạo độ ẩm và óng ả cho tóc mà không gây bết dính. Hỗ trợ phục hồi tóc hư tổn\r\n- Tạo mùi hương dịu nhẹ, cuốn hút cho tóc. Kem ủ Beaua 10 tinh chất là giải pháp hoàn hảo cho chị em đang gặp các vấn đề về tóc. Sản phẩm lành tính với da đầu nên có thể dùng cho người có da nhạy cảm hoặc đang gặp các vấn đề về da đầu.'),
(114, 'Hair', 'H011', 'DG', 'Dầu gội phục hồi tóc hư tổn Asmaa Organic Argan Oil ', 'https://japana.vn/uploads/product/2018/10/16/1539660013-c-hoi-toc-hu-ton-asmaa-organic-argan-oil-500ml.jpg', 600000, '', 600000, '- Chăm sóc và nuôi dưỡng da đầu khoẻ mạnh, đồng thời hạn chế các vấn đề về da đầu như gàu, vảy nến, eczema...\r\n\r\n- Thành phần được chiết xuất từ thiên nhiên nên an toàn và không chứa chất tẩy rửa, không làm gây ngứa, gàu hay gãy rụng tóc...\r\n\r\n- Hỗ trợ tăng cường chất dưỡng ẩm và tránh tình trạng tóc khô xơ và giữ tóc luôn mềm mại, bóng mượt suốt cả ngày.\r\n\r\n- Cung cấp dưỡng chất nuôi tóc khoẻ mạnh từ gốc đến ngọn, đồng thời bảo vệ tóc tránh những tác nhân gây hư tổn như nhiệt độ, ánh nắng mặt trời, hoá chất...'),
(115, 'Hair', 'H012', 'DG', 'Dầu Gội TRESemmé', 'http://hangtieudungmy.com.vn/image/cache/catalog/dau-goi-tresemme-healthy-volume-946ml-800x800.jpg', 260000, '', 260000, 'Dầu gội TRESemmé 24 giờ sẽ  giúp bạn duy trì được độ phồng và bồng bềnh cho tóc cả ngày, giúp bạn dễ quản lý mái tóc mà tóc không bị xẹp xuống. Với hệ thống dưỡng chất như protein từ tơ sẽ giúp bạn tạo nên mái tóc với độ phồng tự nhiên theo cấu trúc tự nhiên của tóc, không bị xẹp xuống và cung cấp độ dưỡng ẩm phù hợp. Công thức nhẹ dịu phù hợp sử dụng hằng ngày. '),
(116, 'Hair', 'H013 ', 'DG', 'Dầu gội dưỡng tóc NEXXUS', 'https://www.shophangmy.vn/images/detailed/103/81YtkyyvEDL-www.shophangmy.vn-1536402600.jpg', 865000, '', 865000, 'Dầu gội dưỡng tóc NEXXUS New York salon care dành cho tóc khô, được nhập khẩu từ Mỹ, giúp bổ sung dưỡng chất tăng độ ẩm tối đa cho tóc xơ, giúp giữ ẩm cho tóc 24 giờ. NEXXUS New York salon care chuẩn salon với công thức chế tạo không chứa silicone. Thẩm thấu trong từng sợi tóc và duy trì vẻ đẹp tự nhiên của tóc.'),
(117, 'Hair', 'H014', 'DG', 'Dầu gội KLORANE - Ngăn ngừa rụng tóc', 'https://www.vivalust.vn/wp-content/uploads/2018/04/dau-goi-klorane.jpg', 280000, '', 280000, 'Nhờ chiết xuất từ vỏ cây Canh-ki-na với hoạt chất chính là Quinine, dầu gội trị rụng tóc Klorane sẽ tăng cường vi tuần hoàn, kích thích chuyển hóa tế bào và mang lại sức sống cho nang tóc. Ngoài ra, dầu gội trị rụng tóc Klorance còn có thêm thành phần các vitamin nhóm B (B5, B6, B8) có tác dụng giúp tóc tăng trưởng và đảm bảo độ chắc khỏe cho tóc, ngăn ngừa, trị rụng tóc.'),
(118, 'Hair', 'H015', 'DG', 'DẦU GỘI CEDRAT PURIFYING SHAMPOO', 'https://product.hstatic.net/1000032844/product/dau-goi-cho-nam-l_occitane-cedrat-purifying-shampoo-250ml_large.jpg', 550000, '', 550000, 'Giàu tinh chất Thanh Yên hữu cơ vùng Corsican, với đặc tính tràn đầy năng lượng, và tinh dầu hương thảo tinh khiết, dầu gội giúp tái cân bằng da đầu. Hồi phục sự mềm mại và bóng sáng, giúp tóc tỏa hương thơm tươi mát và đầy nam tính. Tóc trờ nên mềm mại, thưa và dễ chải.'),
(119, 'Body', 'B001', 'ST', 'Honey Shower', 'https://file.yes24.vn/Upload/ProductImage/minhmy2018/1979128_L.jpg', 230000, '', 230000, 'Thông tin sản phẩm\r\n\r\n- Sử dụng hàng ngày cho bạn một làn da rạng ngời, khỏe khắn đầy sức sống.\r\n\r\n- Hương thơm nhẹ nhàng, giúp cơ thể suốt ngày thơm mát.\r\n\r\n- Chiết xuất từ mật ong và công thức an toàn phù hợp với mọi loại da.\r\n\r\nCách sử dụng\r\n\r\n- Cho một ít sữa tắm ra lòng bàn tay, hoặc bông tắm tạo bọt và massage nhẹ nhàng.\r\n\r\n- Tắm lại sạch với nước.'),
(120, 'Body', 'B002', 'ST', 'Deep Comfort Body Wash', 'https://debenhams.scene7.com/is/image/Debenhams//20714376109?wid=675&hei=675&fmt=webp&qlt=90', 150000, '', 150000, 'Thông tin sản phẩm\r\n\r\n- Kết cấu kem mịn đậm đặc, nhẹ nhàng làm sạch và làm dịu ngay cả làn da khô nhất.\r\n\r\n- Bọt kem được rửa sạch một cách dễ dàng mà không hề tước đi độ ẩm tự nhiên của làn da.\r\n\r\n- Giữ làn da cảm giác thoải mái, đủ ẩm.\r\n\r\nCách sử dụng\r\n\r\n- Làm ướt cơ thể.\r\n\r\n- Thoa đều và massage sản phẩm trên da, thích hợp khi sử dụng bông tắm.\r\n\r\n- Rửa lại với nước sạch.'),
(121, 'Body', 'B003', 'ST', 'Sữa Tắm Trị Mụn Lưng Innisfree Bija Trouble Liquid Body Cleanser', 'https://myphamnanavungtau.com/wp-content/uploads/2018/07/sua-tam-cho-da-mun-innisfree-bija-trouble-liquid-body-cleanser-6.jpg', 250000, '', 250000, 'Innisfree Bija Trouble Liquid Body Cleanser với thành phần lành tính từ dầu quả Bija quý giá có tác dụng làm dịu và chăm sóc làn da bị mụn ở lưng, ngực hoặc tay chân… Bên cạnh đó, 2% Salicylic Acid có tính năng tẩy tế bào chết, giảm viêm và kháng khuẩn mụn.'),
(122, 'Body', 'B004', 'ST', 'Body White Moisture Body Wash', 'https://media.sheis.vn/beautyProductPhoto/g5/s600x600/HanaTara-1412134174_Body_Blossom_White_Moisture_Boday_Wash-635736083835650821.jpg', 300000, '', 300000, 'Thông tin sản phẩm\r\n\r\n- Bọt xà phòng mềm mịn giúp rửa sạch chất bã thừa trên da một cách mát sạch, mang đến làn da sạch sẽ và mướt mịn.\r\n\r\n- Hương thơm tươi mát và sảng khoái trên toàn cơ thể được âm thầm duy trì mang đến sức sống cho làn da mỏi mệt.\r\n\r\nCách sử dụng\r\n\r\n- Cho một lượng sản phẩm vừa đủ vào bông tắm và tạo bọt\r\n\r\n- Thoa đều bông tắm lên cơ thể, mát xa và rửa lại với nước ấm\r\n\r\nThành phần\r\n\r\nSữa, dừa, đường mía, bơ hạt mỡ shea butter và chiết xuất từ trenella fuciformis'),
(123, 'Body', 'B005', 'ST', 'Body And Soul Body Wash', 'https://product.hstatic.net/1000252720/product/bd272101163_body_soul_love_hawaii_body_wash_new__l_master.jpg', 300000, '', 300000, 'Thông tin sản phẩm\r\n\r\n- Nhẹ nhàng lấy đi các bụi bẩn và làm sạch da, đồng thời bổ sung dưỡng chất, tăng cường ẩm giúp da không bị khô và hỗ trợ làm mịn da.\r\n\r\n- Hương thơm ngọt nào, khó cưỡng cho bạn thăng hoa trong cảm xúc. Có nhiều mùi hương để bạn lựa chọn.\r\n\r\nCách sử dụng\r\n\r\n- Làm ướt cơ thể, xoa đều sữa tắm lên da và massage nhẹ nhàng rồi tắm lại với nước.\r\n\r\nThành phần\r\n\r\nVitamin E, Lô hội'),
(124, 'Body', 'B006', 'DT', 'Sữa Dưỡng Thể St.Ives Oatmeals & Shea Butter Body Lotion', 'https://media-ak.static-adayroi.com/sys_master/hd6/h54/17230755266590.jpg', 170000, '', 170000, 'Thông tin sản phẩm\r\n\r\n- Cung cấp độ ẩm và khoáng chất giúp nuôi dưỡng sâu làn da mà không gây bết dính.\r\n\r\n- Kết cấu đặc sệt, giàu dinh dưỡng và dễ dàng thẩm thấu vào da.\r\n\r\nCách sử dụng\r\n\r\n- Dùng sau khi tắm, lấy một lượng vừa đủ thoa lên da.\r\n\r\n- Massage và vỗ nhẹ để dưỡng chất dễ dàng thẩm thấu.'),
(125, 'Body', 'B007', 'DT', 'Black Pomegranate Voluming Serum', 'http://skinfoodstore.net/upload/product/2013/1011/black_pomegranate_serum_skinfoodstore.jpg', 170000, '', 170000, 'Thông tin sản phẩm\r\n\r\n- Sản phẩm bao gồm 1 chai và 1 gói bột riêng biệt: ống tinh chất chứa Black Pomegranate Voluming Effector™ và một gói bột riêng biệt, dùng trộn với nhau trước khi dùng.\r\n\r\n- Gói bột đi kèm với ống tinh chất chứa 7 thành phần hoạt tính: Dẫn xuất vitamin C, vitamin E acetate, vitamin B5, vitamin F (Linoleic acid), vitamin H (Biotin), GLA (gamma linolenic acid), and CoEnzyme Q10.\r\n\r\n- Bảy thành phần hoạt tính trong gói bột, cùng với ống tinh chất riêng biệt cho hiệu quả tối ưu. \r\n\r\nCách sử dụng\r\n\r\n- Trộn lẫn gói bột và ống tinh chất lại với nhau. Lắc hỗn hợp mạnh cho đến khi gói bột hoàn toàn tan hết.\r\n\r\n- Để có hiệu quả tối ưu, để tinh chất đã trộn trong vòng 24h trước khi dùng.\r\n\r\n- Dùng tinh chất trong vòng 5 tháng sau khi mở nắp.'),
(126, 'Body', 'B008', 'DT', 'Sữa dưỡng thể hương nước hoa/ Perfumed Body Lotion 200ml', 'https://product.hstatic.net/1000274411/product/200ml_perfumed_body_lotion_large.jpg', 310000, '', 310000, 'Sữa dưỡng thể hương nước hoa/ Perfumed Body Lotion 200ml Sữa dưỡng thể cung cấp ẩm và nuôi dưỡng da với công thức đặc biệt cho cảm giác sử dụng thật mỏng nhẹ mà không dính rít. Hương nước hoa hòa quyện ngọt ngào thư thái ngay khi thoa và lưu trên da một mùi hương nồng nàn, quyến rũ đầy kiêu sa. Chiết xuất Dâu tằm Morus Alba (Mulberry) giúp ức chế hoạt động của Tyrosinase giảm sự hình thành các đốm sắc tố Melanin, cho làn da sáng và đều màu. Chiết xuất Aloe Vera và Olive thẩm thấu sâu giúp da dưỡng ẩm, mềm mịn đầy sức sống. Hương thơm nước hoa ngọt ngào mà nồng ấm từ cam Bergamot, hoa Violet và Vani lưu thật lâu cho bạn sắc mùi rất riêng đầy duyên dáng.'),
(127, 'Body', 'B009', 'DT', 'Sữa dưỡng thể Dark Kiss', 'https://myphamxachtayhcm.com/kcfinder/upload/images/sua-duong-the-dark-kiss-bath-body-works-body-lotion.jpg', 250000, '', 250000, 'Sữa Dưỡng Thể Bath & Body Works Dark Kiss Shea & Vitamin E Body Lotion (236ml) với công thức dưỡng da độc đáo từ bơ hạt mỡ, tinh dầu Jojoba, vitamin E giúp bảo vệ, nuôi dưỡng cung cấp dưỡng chất và bổ sung độ ẩm cho làn da suốt cả ngày. Mặc dù không lưu mùi hương đậm đặc như khi dùng nước hoa, mà sẽ mang mùi hương thoang thoảng, lúc ẩn và lúc hiện, tăng thêm sự quyến rũ cho chị em phụ nữ.'),
(128, 'Body', 'B010', 'DT', '', 'https://www.smallflower.com/prodimages/224878-DEFAULT-l.jpg', 380000, '', 380000, 'Thông tin sản phẩm\r\n\r\n- Mang đến làn da của bạn sự mịn màng và hương thơm nhẹ nhàng.\r\n\r\n- Công thức dễ thẩm thấu và không dính rít.\r\n\r\n- Không chứa paraben, không chất tạo màu.\r\n\r\nCách sử dụng\r\n\r\n- Thoa sản phẩm lên cơ thể và massage nhẹ nhàng.'),
(129, 'Body', 'B011', 'BB', 'Bom tắm LUSH - The Big Sleep Bath Bomb', 'https://cf.shopee.vn/file/5c368c76bc3a70dc6ed05567ad6c2388', 270000, '', 270000, '- Thành phần chính của Big Blue là một loại tảo bẹ gọi là rong biển nổi tiếng, làm mềm trong nước nóng của bạn. Rong biển Arame giàu vitamin và khoáng chất bao gồm i-ốt, giúp điều hòa sự trao đổi chất. Muối biển làm mềm da, giúp loại bỏ các tế bào da chết, trong khi dầu chanh làm sạch , dầu hoa oải hương là chất khử trùng và làm sạch\r\n- Arame là một loại rong biển tự nhiên giàu vitamin và khoáng chất, bao gồm canxi, đồng, magie, sắt, kẽm và iốt giúp làm mềm và làm sạch da + Muối biển làm sạch hiệu quả, làm mềm và làm ẩm da, loại bỏ tế bào da chết mà không tước đi quá nhiều dầu tự nhiên trên da trả lại làn da sạch mà vẫn giữ được độ ẩm trên da\r\n- Tinh dầu được chiết xuất từ ​​da của quả chanh và được sử dụng để làm sạch da và làm mới tâm trí. Dầu chanh có đặc tính kháng khuẩn trên da, làm sạch và làm sáng da khi bôi tại chỗ. Nó chứa axit alpha-hydroxy, hoặc AHA, là enzyme làm sạch da bằng cách phá vỡ bụi bẩn, dầu dư thừa, sản phẩm như tạo nên và da chết, giúp làn da tươi mới trở lại\r\n- Dầu hoa oải hương : cân bằng làm dịu da ,phù hợp với làn da bị kích ứng , nó cũnglàm dịu tâm trí và giúp đỡ một giấc ngủ yên tĩnh sau khi tắm'),
(130, 'Body', 'B012', 'BB', 'Watermelon Large Bath Fizzy', 'https://i.pinimg.com/736x/36/89/f6/3689f6aafd661c65cb399e44892452d5.jpg', 300000, '', 300000, 'Fizz & Bubble Watermelon Bath Fizzy là một niềm vui và mới mẻ trong các món ăn mùa hè mà tất cả chúng ta đều thích ăn! Thưởng thức một bồn tắm đầy mùi hương trái cây và làm dịu làn da của bạn trong thời gian giật gân ngọt ngào này! Với đường kính 70mm (xấp xỉ 2,75 inch), chiếc bồn tắm Fizz & Bubble này có trọng lượng khoảng 6,5 ounce, và có hỗn hợp 8-Oil siêu dưỡng ẩm bao gồm một hỗn hợp pha trộn cẩn thận của Aloe Vera, Dừa, Grapeseed, Sweet Almond, Olive , Dầu bơ, hướng dương và Jojoba và được hoàn thành với muối Epsom, vitamin E và đất sét Mica.\r\n\r\nLỢI ÍCH CHÍNH:\r\nDầu ô liu - Chứa ba chất chống oxy hóa chính, chống lão hóa và sẽ không làm tắc nghẽn lỗ chân lông của bạn.\r\nDầu hướng dương - Được biết đến là có hiệu quả chống lại mụn trứng cá, chàm, viêm, đỏ và kích ứng da\r\nDầu dừa - Kem dưỡng ẩm tuyệt vời\r\nDầu hạnh nhân ngọt ngào - Cho làn da mịn màng và làm sạch sâu\r\nDầu hạt nho - Chứa axit linoleic giúp củng cố màng tế bào và cải thiện chất lượng tổng thể của làn da của bạn\r\nDầu bơ - Tăng cường hiệu quả làm mịn và có thể tăng khả năng tạo ra các tế bào mạnh hơn và khỏe hơn cho làn da của bạn\r\nDầu lô hội - Nó có tác dụng chống viêm, chống vi khuẩn, chống vi rút, kháng nấm, chống oxy hóa và làm se da\r\nDầu Jojoba - Hoạt động như một chất chống viêm và làm dịu da bị kích thích.'),
(131, 'Body', 'B013', 'BB', 'DA BOMB Amazeballs', 'https://i.pinimg.com/originals/ea/e4/c1/eae4c1829c8243515a54f9b08cd3b5f4.jpg', 310000, '', 310000, 'Thả 1-3 hỗn hợp nước xả berry hỗn hợp này vào bồn tắm của bạn và xem khi chúng xì hơi và quay tròn, giải phóng các thành phần làm dịu da và dầu. Mỗi fizzers thơm này có một bất ngờ thú vị nhỏ bên trong! Giữ mỗi fizzer trong tay khi nó tan biến để tìm thấy sự bất ngờ. Hoàn hảo cho cả người lớn và trẻ em. Mọi người đều thích sự bất ngờ! Được tạo bởi một cặp chị em tuổi teen. Được làm thủ công ở Mỹ chỉ bằng một vài nguyên liệu đơn giản. Mỗi fizzer là 1,5 ounce. \r\nLưu trữ ở nơi khô ráo, thoáng mát trong bao bì gốc.\r\n\r\nThận trọng: Các bộ phận nhỏ. Không dành cho trẻ em dưới 3 tuổi.\r\n'),
(132, 'Body', 'B014', 'BB', 'Viên Sủi Bồn Tắm The Comforter Bath Bomb - Lush ', 'https://cf.shopee.vn/file/94f77dabac4110df29ccffd39d686ea5', 315000, '', 315000, '- Cassis tuyệt đối mang lại hương thơm sâu, đen ,các loại tinh dầu khác nhau có thể được pha trộn với nó để mang lại hương trái cây, ngọt, đắng hoặc gỗ để đem lại một mùi hương tuyệt vời\r\n- Dầu Bergamot làm mới làn da và giúp tóc bóng mượt. Hương thơm nồng nàn, cao độ của nó làm sạch tâm trí và khuyến khích một cảm giác hạnh phúc.\r\n- Dầu cây bách có thể được sử dụng tại chỗ trên da để làm dịu cơ bắp đau nhức, tăng lưu thông máu và giúp giải độc cho da .Dầu cây bách gần như không màu và có mùi thơm năng lượng gỗ sạch được sử dụng như một phần của hỗn hợp nước hoa và hương liệu. Hương thơm của nó có thể làm dịu căng thẳng , làm cho nó trở thành một thành phần tuyệt vời trong các sản phẩm tắm. Nó đặc biệt thoải mái trong mùa đông vì nó được cho là kích thích cảm giác vui vẻ và hạnh phúc.'),
(133, 'Body', 'B015', 'BB', 'Detoxifying Epsom Salt Treatment Bath Bomb Citrus Mint', 'https://media.sheis.vn/beautyPhotoBanner/g70/s/Beauty-43330b25-50df-455d-966c-3d767995349a-sheIs_0e97683a-1a08-4ea6-b0bf-523e7ded213a57.jpg', 350000, '', 350000, '- Hương bưởi Bergamot và cam Neroli cùng hòa quyện vào hương trà xanh tươi mát đặc trưng của Tea and Sympathy. \r\n- Lượng vitamin C dồi dào sẽ thanh tẩy làn da của bạn cũng như đem lại sự tươi trẻ và rạng rỡ bất ngờ. \r\n- Ẩn giấu trong ấm trà xinh xắn này còn là những bông hoa thanh cúc đẹp đẽ mang đến sự mát mẻ từ những cánh đồng xanh tốt cùng một chút kích thích nhẹ nhàng đồng thời còn có tác dụng thu gọn lỗ chân lông rất tốt.');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=134;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
